add lots of comments about tiles to functions-branch
WarsWorld/WarsWorld pull request #106
Opened 2023-05-07 07:48 UTC by megagreg72

2023-05-07 08:09 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> +};
I *think* I figured out what this function does. Let me know if this is correct :)

2023-05-07 08:15 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> + * Caculate the defense of a unit.
```suggestion
 * Calculate the defense of a unit.
```

2023-05-07 18:36 UTC, FunctionDJ reviewed
the code changes make the code more complicated in my opinion. "manMadeMovementCosts" is a new concept that needed to be explained instead of just leaving the previous system that simply created some reusable tile properties.
there's also more redundancy for lab, comtower, unusedSilo and usedSilo.
the file is also now contains about 35 more lines of code that don't change the behaviour of the code as far as i can tell and which don't make the code more maintainable or understandable as i've explained at the start.

2023-05-07 18:36 UTC, FunctionDJ commented on src/shared/match-logic/tiles.ts
> +  // `as const satisfies ...` allows us to essentially define a custom type with exactly
`as const` is not needed for this. all it does is make all properties `readonly` and turns the value types from regular primitives to literals.
i'm using `satisfies` in many places so for consistency you'd either need to copy this explanation to every instance or you just don't and let someone use Google or watch a TS tutorial for a change.
there are many other TS concepts i consider worth explaining like mapped types because unless you know what they're named, there's no keyword you can put into a search engine to learn about it.

2023-05-07 18:36 UTC, FunctionDJ commented on src/shared/match-logic/tiles.ts
> +   * However, *we* are currently planning to store health as a number from 0 to 1,
this `*` was a mistake. we store HP as 0-100 https://github.com/WarsWorld/WarsWorld/blob/cc52eb92d3c5835444d5ea59feab544c7e932a46/src/server/schemas/unit-traits.ts#L6

2023-05-07 18:52 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> +  // `as const satisfies ...` allows us to essentially define a custom type with exactly
ah, you are right.  I used it with `as const` out of habit but in this case that isn't needed

2023-05-07 19:02 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> +const landMovementCosts = {
I was thinking that "Movement costs which are shared" and "satisfies Partial<TileMovementCosts>;" would clarify it, but I agree that `commonLandMovementCosts` is better.

2023-05-07 20:03 UTC, FunctionDJ requested changes

2023-05-07 20:03 UTC, FunctionDJ commented on src/shared/match-logic/tiles.ts
> + * Every unit has exactly one "movement type", for example tanks have type "treads".
i think the info of this specific line is common knowledge in the AW community.

2023-05-07 20:03 UTC, FunctionDJ commented on src/shared/match-logic/tiles.ts
> + * @param weather The current weather, e.g. "rain"
the examples for type values are not needed because a developer can just use their editor/IDE to see which values are possible or use jump-to-definition.

2023-05-07 20:06 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> + * TODO: Create a TileType for a "broken pipe seam".
I think it is weird that broken pipe seams are considered a variant of plains, but used missile silo is not a variant of missile silo.  Both variants have gameplay implications (Jake's power for plains).
But thanks for letting me know how it is currently handled 👍

2023-05-07 20:17 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> + * Currently we use approach (2).
I was thinking we might want to pre-calculate the movement costs as space-vs-time optimization, but we can probably get the best of both worlds by just memoizing the getter function.

2023-05-07 20:34 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> + * - Any building which *could have* produced a unit
I can see where you are coming from, but I prefer this.
I like that it provides a logical *explanation* for why piperunners can move through bases etc.
I suppose it is inevitable that everyone likes their own code 😄

2023-05-07 20:36 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> +/** Pipes and (unbroken) pipe seams are exactly the same */
it saves a dev 5 seconds of scrolling down to see usage 🤷‍♂️

2023-05-07 20:38 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> + * because they have the same defense and movement properties.
ok, I removed the kinda-suggestion and just made two notes on `TileType` itself about pipe seam => plains and silo => used silo

2023-05-07 20:40 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> + * Every unit has exactly one "movement type", for example tanks have type "treads".
even with AW knowledge, "movement type" could be something like `'normal' | 'transport-unload'` or `'normal' | 'lash-power' | 'sturm'`

2023-05-07 20:46 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> + * @param weather The current weather, e.g. "rain"
fair enough, I don't mind removing these examples because I explained movement type above.

2023-05-07 20:48 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> + * @param weather The current weather, e.g. "rain"
done 👍

2023-05-07 21:04 UTC, FunctionDJ requested changes

2023-05-07 21:04 UTC, FunctionDJ commented on src/shared/match-logic/tiles.ts
> + * Every unit has exactly one "movement type", for example tanks have type "treads".
https://awbw.fandom.com/wiki/Units#Movement

2023-05-07 21:16 UTC, FunctionDJ commented on src/shared/match-logic/tiles.ts
> + * @param weather The current weather
do the movementType and weather `@param`s really add substantial information here? i think they can be omitted.

2023-05-07 21:46 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> + * @param weather The current weather
I will not remove these. I added back examples for `tileType` and `movementType` to make them more useful again.

2023-05-08 00:32 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> +};
fixed hp bug

2023-05-08 01:40 UTC, megagreg72 commented
I we resolved all of Function's suggestions except for some comment-related suggestions where we will "agree to disagree".
I'm ready to merge this whenever.

2023-05-08 13:25 UTC, merged