prettier max line length for readability
WarsWorld/WarsWorld pull request #122
Opened 2023-05-14 04:47 UTC by megagreg72

I arbitrarily chose 120 chars, but we can debate about the correct number.

2023-05-14 06:22 UTC, megagreg72 commented on .github/dependabot.yml
> +    directory: "/"
I'm not sure familiar with `.yml` files, but a quick google search suggests that `"` is the same as `'` so our prettier rule could apply here too

2023-05-14 06:23 UTC, megagreg72 commented on package.json
> +    "lint:fix": "npm run lint:prettier:fix && npm run lint:eslint:fix",
fix lint scripts

2023-05-14 06:29 UTC, megagreg72 commented on CONTRIBUTING.md
> -
ironic

2023-05-14 06:37 UTC, megagreg72 commented on src/shared/types/events.ts
> +   * and calculating HP later.
```suggestion
   * TODO: Consider sending just the luck roll(s) for the event,
   *       and calculating HP later.
```

2023-05-14 18:14 UTC, FunctionDJ requested changes

2023-05-14 18:14 UTC, FunctionDJ commented on .eslintrc.js
> +        ignoreStrings: true,
if we don't ignore comments, i say we shouldn't ignore strings and template literals too. URLs sounds like it would be too annoying though and limiting them isn't all that useful for readability.

2023-05-14 18:14 UTC, FunctionDJ commented on package.json
> +    "lint:fix": "npm run lint:prettier:fix && npm run lint:eslint:fix",
why so many scripts? our eslint config is using the prettier plugin. shouldn't there be no reason to run prettier standalone?
if eslint doesn't run on non-code files, can we fix that?

2023-05-15 01:38 UTC, megagreg72 commented on .eslintrc.js
> +        ignoreStrings: true,
right, I'm thinking about enabling that later, I just wanted to keep this PR small 👍

2023-05-15 01:40 UTC, megagreg72 commented on package.json
> +    "lint:fix": "npm run lint:prettier:fix && npm run lint:eslint:fix",
I think that eslint might be ignoring non-code files because of this
"eslint src --ext \".js,.ts,.tsx\"
```
or maybe eslint just ignores non-code files by default?  can't remember if I tested without that

2023-05-15 01:51 UTC, megagreg72 commented
responded to comments

2023-05-29 01:37 UTC, megagreg72 commented
https://github.com/WarsWorld/WarsWorld/pull/122#discussion_r1193188050
I believe that `eslint` is simply not designed to lint anything except for code files.
`prettier` is designed to lint pretty much anything, so I think we have to run `prettier` by itself if we want to lint non-code files like `README.md`.

2023-05-29 01:55 UTC, megagreg72 commented
ha, our build checks prevented this PR from being merged because the linter was complaining about a comment which was too long.  That was definitely an intentional test of our build system 🤣

2023-05-29 02:00 UTC, megagreg72 commented
hmm, actually it looks like linting takes about 6 seconds longer now (eyeballing some build times for the `lint` step in this PR compared to some other PRs)

2023-05-29 06:08 UTC, megagreg72 commented
I saved about 3 seconds of build time by limiting which files `prettier` checks, to avoid double-checking the files `eslint` would check.
but at what cost? (my sanity)

2023-06-01 21:22 UTC, merged