Home banner and tweaks
WarsWorld/WarsWorld pull request #136
Opened 2023-05-26 16:59 UTC by FemboyDeveloper

### Home Banner
Finished and ready to be merged! Looks slick and modern

### Background
Removed the old background and made a new one that's a mix of Rhett's blue idea and AW1 (AWBW's) background.

### Font Weight and size
Tweaked font sizes and weights, these will work much better and include a wide array of weigths so we can make our fonts bolder or ligther depending on what we need.

### Favicon and logo
Deleted the advance wars logo and put our new logo, added a favicon ico that looks smoooove.

2023-05-26 18:52 UTC, leekahung requested changes
Made a first pass over this. See feedback.

2023-05-26 18:52 UTC, leekahung commented on src/frontend/components/Home/Banner.tsx
> +        className={`@relative @w-screen  @h-100   @bg-cover @bg-[url('/img/layout/homeBanner/gameCollage.jpg')]`}
Lots of extra spaces that can be removed in Line 7

2023-05-26 18:52 UTC, leekahung commented on src/frontend/components/Home/Banner.tsx
> +            "@flex @items-start @gap-10  @backdrop-brightness-[0.40] @w-100 @px-10 @py-40 "
Space issue in Line 11.

2023-05-26 18:52 UTC, leekahung commented on src/frontend/components/Home/Banner.tsx
> +            className="pixelated  "
Space issue in Line 15

2023-05-26 18:52 UTC, leekahung commented on src/frontend/components/Home/Banner.tsx
> +      </p>
I believe these are to test our Typography settings for the website. Think we can safely remove these.

2023-05-26 18:52 UTC, leekahung commented on src/frontend/components/Navbar/Navbar.tsx
>          <button
Button and burger menu seems out of sync when it comes to size. Think we can make the button wrap around the burger icon more.

![Screen Shot 2023-05-26 at 11 26 16](https://github.com/WarsWorld/WarsWorld/assets/14917816/1c99610d-0447-4ced-8645-49339edb3bdb)

2023-05-26 18:52 UTC, leekahung commented on src/frontend/styles/globals.scss
> +    background-color: rgb(146 64 14);
We should think about what other colors we could use for the toggles for dropdown menus and the text color for links. Because it'll be orange/orange.

![Screen Shot 2023-05-26 at 11 24 32](https://github.com/WarsWorld/WarsWorld/assets/14917816/02c3400f-65e7-4dd1-bccc-dec794d6ddb8)

They really should look like links and behave like Links in terms of hover.

https://github.com/WarsWorld/WarsWorld/assets/14917816/e796cdad-2769-494f-8bcf-0b7d0d21b4dd

2023-05-26 18:52 UTC, leekahung commented on src/frontend/styles/grid/global.scss
Not all stylings here is related to the map.

For example, there are some of the player box stylings are in here too (Line 17-52).

![Screen Shot 2023-05-26 at 11 48 38](https://github.com/WarsWorld/WarsWorld/assets/14917816/1f1661d4-8495-40a1-b589-34f5ffbdec4e)

Other things like Lines 54 to 71 (just to name a few) are stylings for other components related to the in-game match page. We should refactor these out into their own file or rename this one and remove all the map related stuff. I've helped parsed down which stylings are important in the feedback.

2023-05-26 18:52 UTC, leekahung commented on src/frontend/styles/grid/global.scss
> -}
Lines 2 to 8 not relevant to mapGrid. Should be refactored out.

2023-05-26 18:52 UTC, leekahung commented on src/frontend/styles/grid/global.scss
> -}
Lines 17 to 71 not relevant to mapGrid. Should be refactored out.

2023-05-26 18:52 UTC, leekahung commented on src/frontend/styles/grid/global.scss
> -      gap: 1rem;
Lines 496 to 499 not relevant to mapGrid. Should be refactored out.

2023-05-26 18:52 UTC, leekahung commented on src/frontend/styles/grid/global.scss
> -  color: black;
Line 73 to 74 not relevant to mapGrid. Should be refactored out.

2023-05-26 18:52 UTC, leekahung commented on src/frontend/styles/grid/global.scss
> -}
Lines 506 to 565 not relevant to mapGrid. Should be refactored out.

2023-05-26 18:52 UTC, leekahung commented on src/frontend/styles/grid/global.scss
> -@screen laptop {
Lines 567 not relevant to mapGrid. Should be refactored out.

2023-05-26 18:52 UTC, leekahung commented on src/frontend/styles/grid/global.scss
> -}
Lines 576 to 588 not relevant to mapGrid. Should be refactored out.

2023-05-26 21:12 UTC, FemboyDeveloper commented on src/frontend/components/Home/Banner.tsx
> +            "@flex @items-start @gap-10  @backdrop-brightness-[0.40] @w-100 @px-10 @py-40 "
I'd say we don't need to point out extra spaces like this, its a bit nitpicky and we can have the linter take care of it later.

2023-05-26 21:24 UTC, FemboyDeveloper commented on src/frontend/components/Navbar/Navbar.tsx
>          <button
This is because you set both as buttons, when neither of them are supposed to be buttons.

2023-05-26 21:29 UTC, leekahung commented on src/frontend/components/Home/Banner.tsx
> +            "@flex @items-start @gap-10  @backdrop-brightness-[0.40] @w-100 @px-10 @py-40 "
When I tried to save this with Prettier, the spacing problem was basically ignored. Would need to be checked out since it might be a formatting issue.

2023-05-26 21:31 UTC, leekahung commented on src/frontend/components/Navbar/Navbar.tsx
>          <button
Could perhaps replace the buttons with a toggleable alternative if buttons are not preferred. Think that should solve these issues.

2023-05-26 21:32 UTC, FemboyDeveloper commented on src/frontend/components/Navbar/Navbar.tsx
>          <button
Yeah, buttons are specifically left for the "click me and let me take you to a link" option, usually you dont use <button> for hover menus or hamburger menus, at least in my experience.

2023-05-26 21:33 UTC, merged

2023-05-27 11:22 UTC, FunctionDJ commented on src/frontend/components/Navbar/Navbar.tsx
>          <button
@FemboyDeveloper buttons are for interactivity, anchor tags (<a>) are for navigation. burger menu is an interactive element and the links are navigation items.

2023-05-27 13:19 UTC, FemboyDeveloper commented on src/frontend/components/Navbar/Navbar.tsx
>          <button
@FunctionDJ I've done [some research](https://www.youtube.com/watch?v=CZGqnp06DnI), it seems we should be using <button> for anything we can click since it helps alot for accessibility and it has alot of other good reasons... (focusable, can be accessed with space and enter, for screen readers it says "button" and not "group"). Seems like I've led you astray @leekahung , your original method of using <button> is correct. 

I'll make a custom styling for regular buttons then, prob will be called .btn or something.