Home three components
WarsWorld/WarsWorld pull request #144
Opened 2023-06-01 20:55 UTC by FemboyDeveloper

Adds small container components and small text components to the home page. Both can be re-used for other pages. Also brings a couple of small tweaks here and there.

2023-06-01 21:59 UTC, leekahung requested changes
Visually, I think it looks pretty great!

Think we can do a more in-depth review after we've merge the previous changes to main into this branch or checkout from main and copy the changes over to here.

2023-06-01 22:13 UTC, leekahung requested changes
Did one minor review, mostly related to curly braces and spaces.

2023-06-01 22:13 UTC, leekahung commented on src/frontend/components/Home/SmallContainer.tsx
> +    <div className={"  @bg-blue-950 @rounded-2xl   "}>
Spacing problem on Line 9, Line 11, Line 17. Other than that, since these are just static classes, we can just use strings without the curly brackets.

2023-06-01 22:13 UTC, leekahung commented on src/frontend/components/Home/SmallContainer.tsx
> +          <strong> {props.title} </strong>
Extra spaces between prop title unlike what we have in Line 21.

2023-06-01 22:13 UTC, leekahung commented on src/frontend/components/Home/ThreeLinesText.tsx
> +        <strong> {props.title}</strong>
Extra spacing in Line 26.

2023-06-01 22:13 UTC, leekahung commented on src/frontend/components/Home/ThreeLinesText.tsx
> +      <div className={"@mt-4 @gap-1"}>{buttonArray}</div>
Can drop the curly braces for className.

2023-06-01 22:13 UTC, leekahung commented on src/frontend/components/Home/Banner.tsx
> +            <button className={"button"}> Play Now</button>
Can drop the curly braces for className.

2023-06-01 22:13 UTC, leekahung commented on src/frontend/components/Home/Banner.tsx
>          className={`@relative @w-screen  @h-100   @bg-cover @bg-[url('/img/layout/homeBanner/gameCollage.jpg')]`}
Just noticed this now, but we could drop the curly braces for className in Line 12 and Line 18.

2023-06-02 16:41 UTC, FemboyDeveloper commented
@leekahung From my experience and knowledge, the code review is meant to make sure the overall structure of the code is readable, flexible and functional (good code).

We really shouldn't bother with extra whitespaces or not using brackets with strings. These changes are trivial and don't make the code more readable or functional. It just makes it harder to focus on what really matters in your review.

stuff like using fragment components (<>) instead of a parent <div> is much better to bring up in a code review because it actually impacts functionality, since those divs can stack and out elements can become nested in multiple divs for no reason.

2023-06-02 19:05 UTC, leekahung commented
> @leekahung From my experience and knowledge, the code review is meant to make sure the overall structure of the code is readable, flexible and functional (good code).
> 
> We really shouldn't bother with extra whitespaces or not using brackets with strings. These changes are trivial and don't make the code more readable or functional. It just makes it harder to focus on what really matters in your review.
> 
> stuff like using fragment components (<>) instead of a parent div is much better to bring up in a code review because it actually impacts functionality, since those divs can stack and out elements can become nested in multiple divs for no reason.

@FemboyDeveloper @FunctionDJ Isn't that the whole point of a code review? If the code base being reviewed already looking "functional" and "structurally-sound", the person couldn't really make out if there's anything wrong, isn't the next thing you're suppose to do is to access the overall quality of the code. Why are you looking down on this?

From what I'm seeing, it's already looking okay. I'm just trying to review portions of the code that are EXCESSIVE and UNNEEDED.

For className, the main reason why there are curly braces in some is because some classes are dynamically called. But in the case of simple static classes, simple double quotes can be used. There's no JavaScript involved at all in the process, so there's no need to have extra calls in the JSX. Why bother bringing up the bracket? Because they're not needed in those cases. It's not bringing the intended effect of "using JavaScript" within JSX.

For the spacing problem, it might not look bad at this point, but what if it's all over the application? Sure JSX/HTML/JS ignore excess space. You might be fine with it, but I'm not. I was hoping the formatter would just pick up all the issues but it didn't.

This is supposed to be a public facing codebase that's meant to be a SUCCESSOR if not COMPETITOR to the existing AWBW codebase. I wanted it to be presentable as QUALITY CODE enough to impress not just in the functional sense, but OVERALL. Which is why these are being pointed out in a CODE REVIEW process. Is that really okay to not address these issues?

I'm taking my own time to ensure the code is both functional and presentable. If I'm being reprimanded for bringing up the tiny details because I couldn't see anything wrong in the big details, I'm done.

2023-06-02 22:31 UTC, FemboyDeveloper commented
@leekahung You need to calm down and stop taking it so personal/to heart. I simply meant that its unnecessary to point out there are two spaces here and there or using braces when they aren't needed. My reasoning is simply put that right now we don't need this over optimizations, we can focus more on having simple code that's functional, flexible and readable.

My time working in the project is limited, so when I come to the code review, it would be better if we focus on the big picture over minor details such as an extra space. That way I can keep using my time to make this project a reality.

I prefer being told that I'm misusing a certain method or component or that my css could be optimized by using xyz. That is much more useful and impactful to the project overall.

If you think everything is right, you can simply type "LGTM" which means, looks good to me.

I appreciate your passion for making sure all the little optimizations and detaills are as best as possible. But instead of writing it in the comments, why don't you just make those changes yourself? A small commit in my PR with just deleting spaces or unnecessary braces would be very appreciated. I'd be happy to let you keep everything as tidy as you like. 

And again, I didn't mean to offend you, I'm sorry if I came across that way. But please, do know that in this career, people will question and criticize your work. It's not good to take things so personal, it adds friction to your relationship with others. Soft skills as a developer are extremely important. If you land a job in the field, there might be rough senior devs and if you lash out at them it could cost you your job. Your response is an overreaction to what I said.

In no way you are being reprimanded or punished, I'm simply asking to not make a comment for each of these extra spaces since the PR gets littered with alot of comments about small things that take the focus away from the big picture.

Your time and effort are always appreciated.

2023-06-03 00:34 UTC, leekahung commented
> @leekahung You need to calm down and stop taking it so personal/to heart.
>
> I appreciate your passion for making sure all the little optimizations and detaills are as best as possible. But instead of writing it in the comments, why don't you just make those changes yourself? A small commit in my PR with just deleting spaces or unnecessary braces would be very appreciated. I'd be happy to let you keep everything as tidy as you like.

I'm trying hard not to take this personally. But the fact that the fixes to spacings that I've made in the branch gets overwritten, it's hard not to think if it's being made intentionally. I don't understand why they'll pop up again after I went in to fix it. Extra spaces or braces? Sure I can fix them, but how would I know in the future if they'll just be disregarded?

> I simply meant that its unnecessary to point out there are two spaces here and there or using braces when they aren't needed. My reasoning is simply put that right now we don't need this over optimizations, we can focus more on having simple code that's functional, flexible and readable.

No, it's not unnecessary. It points to the level of quality we wish to project into the project. This is not even an optimization. At the moment it's fine because it's only in a few places, which is good. We can catch them early on and fix it. But what if it continues throughout the codebase? It's not like everyone is on the save wavelength when it comes to what it means to be "function", "flexible", and "readable".

For me "function" means that the code works as its intended, "flexible" means it's good for expansion or refactoring, "readable" means if the code could be read EASILY without confusion. Did the spaces in there have a purpose? What of the curly braces? It's why they're pointed out. If they're not there on purpose, we can fix it. If they are, they can be addressed at the very least if not fixed. Not straight up disregard as "it's not important because they don't affect the codebase".

It's not the best analogy and it's very much exaggerated in this example but it's like trying to write paragraphs without punctuations is it still readable without them yes of course is it enough to give the message across absolutely it just make a lot less sense from someone who's trying to read this from the outside but it still works and it can be expanded upon but you can see how it could be different for someone else

> My time working in the project is limited, so when I come to the code review, it would be better if we focus on the big picture over minor details such as an extra space. That way I can keep using my time to make this project a reality.

And I'm trying to give my 2 cent in the project as well. Of course having comments with major revisions might be needed at time, but it shouldn't be a bad thing if the reviews come back with a lot of small comments. It means someone is taking their time to actually GO THROUGH the code and not just skimming over.

> I prefer being told that I'm misusing a certain method or component or that my css could be optimized by using xyz. That is much more useful and impactful to the project overall.
> 
> If you think everything is right, you can simply type "LGTM" which means, looks good to me.

Which I perfectly understand. If I were to use something wrong, I personally would like them to be pointed out so that I can correct them and avoid them in the future. But that mentality should be carried over to the code as well, should it not? Not just the method or component. We shouldn't be limiting ourselves to that.

> And again, I didn't mean to offend you, I'm sorry if I came across that way. But please, do know that in this career, people will question and criticize your work.

That much I understand. First-hand no less. Function had criticize my work before and it was a lot to take in (and I mean a lot). But at the very least they were constructive and directed at the problem, which I very much appreciate. I'm learning a great deal of things from those comments/reviews and I do my best to at least address them with a proper response if not outright fixing them. If there's a problem here that seems to be an issue, I could avoid it next time at the very least.

>  It's not good to take things so personal, it adds friction to your relationship with others. Soft skills as a developer are extremely important.

If communication is a problem, why not directly address the point like: "you're right, the spaces there seems to be extraneous. We should probably fix them soon if not now, perhaps in a latter PR." Or if you think they're not necessary/important, "no, I wish to keep those there because of [reason 1] and [reason 2]".

Not "it is not important, please just check if my code works instead". That was not the main point of those reviews or comments. It was just related to that line/line of issue. There could be other comments or reviews on functionality no? It's part of the code-review after all, they could come separately.

> If you land a job in the field, there might be rough senior devs and if you lash out at them it could cost you your job. Your response is an overreaction to what I said.

First of all, this was actually brought up very plainly. And this was not the first PR which ask that thing. The only reason why it got to this point was because it was ignored or not addressed. There wouldn't even be such a reaction if it was address properly. I'm simply pointing out that there's a quality issue if you're not going to address them. If you don't want to address them, okay. Let someone else do it (they can see the comments). And if they're going to fix the problem for you, don't go overwriting their fixes unless you have a good reason for it (e.g. breaking changes, introducing bugs, etc.).

> In no way you are being reprimanded or punished, I'm simply asking to not make a comment for each of these extra spaces since the PR gets littered with alot of comments about small things that take the focus away from the big picture.

And I don't see it as a problem? It'll let the author and other users know that there are potential issues to be fixed, but the PR is still very much relevant.

Did you not see my earlier comment for request changes? "Did one minor review, mostly related to curly braces and spaces."

It's "minor". It suppose to be "minor". And each comment are targeted (I've even placed Line numbers for those lines). That way it'll be simple to deal without losing focus on other parts of the code. And what do I get as a response?

> We really shouldn't bother with extra whitespaces or not using brackets with strings. These changes are trivial and don't make the code more readable or functional. It just makes it harder to focus on what really matters in your review.

2023-06-03 02:50 UTC, FemboyDeveloper commented
Dude I don't know what to tell you. Im coding to make this project functional, if I change something in VSCode, sometimes I click at the end of a space and press space again and now there are two spaces. If I write a prop or classname, the IDE adds the brackets automatically.

 These things don't matter at all. You are putting this project up in the heavens as if thousands of devs will have to work on it so we have to make sure its written perfectly.  I'm happy with having "good" code, I don't need to go above and beyond and make sure every single character in the code has a specific use and purpose. 

Why bother spending our time making sure every line has no extra spaces or unnecessary brackets? what are the returns from that? did the code improve? is it more readable now? any pros? Don't even think about saying an extra space hurts readability. No, there is absolutely nothing coming out of it, the code is just a tiny, miniscule bit more tidy now. But the time invested into this task was significant. 

The issue is so tiny I don't even realize when you fix it. You gotta let go, stop micromanaging and focus on the macro better. Nobody in the world, not your future boss and not your future users will give half a fuck about your code having 2 more braces or one extra space. They care if the app runs well and the code can be edited by someone else easily, not if it was written with APA standards.

You can continue working on the project if you like, but don't write a dozen comments about extra spaces or brackets on PRs. That adds absolutely nothing but litter. Just makes it so the next person checking the PR has to scroll through a dozen comments just pointing out there's an extra space (which fucking adds nothing) and makes it hard to find out the discussions and issues that matter. 

Dealing with this pointless shit stresses me and wastes my time. If you are going to keep this up, don't let the door hit you on the way out.

2023-06-03 02:51 UTC, merged

2023-06-03 03:22 UTC, leekahung commented
I'm going to drop this topic. I think it's fair say that we both disagree on what is considered "good" code. Not going to say which is correct. I'll leave that to the others. If they fix it, all good. If they don't fix it, still fine.