News Page Updates
WarsWorld/WarsWorld pull request #150
Opened 2023-06-06 01:20 UTC by leekahung

Created new components for News Page, including cards for news posts and a dedicated "featured" post at the top. Routed news to /news.

https://github.com/WarsWorld/WarsWorld/assets/14917816/dcc267af-f419-4dc4-9c86-284a7a14b399

Made contents within new page to be responsive.

https://github.com/WarsWorld/WarsWorld/assets/14917816/7f87682c-69d3-4926-a25f-8d337845652e

https://github.com/WarsWorld/WarsWorld/assets/14917816/20a99d0c-07db-4f49-896e-9e1a0f4f52bc

2023-06-06 18:04 UTC, FemboyDeveloper requested changes
Overall looks good to me. 

Only issues I found are that the big/center card isnt very responsive on bigger sizes, everything else looks great!
![image](https://github.com/WarsWorld/WarsWorld/assets/96269542/74185936-3dac-43f6-9afd-7808c6e821c7)

2023-06-06 22:25 UTC, leekahung commented
> Only issues I found are that the big/center card isnt very responsive on bigger sizes, everything else looks great! ![image](https://user-images.githubusercontent.com/96269542/243787237-74185936-3dac-43f6-9afd-7808c6e821c7.png)

Got it updated. Should be manageable for larger screens now. Used width 60vw for the feature picture and maxWidth 20vw for the textbox

2023-06-08 19:21 UTC, leekahung commented
Included updates to combine the two card components into one and removed the hover shadow.

2023-06-10 14:53 UTC, FemboyDeveloper commented on src/frontend/components/news/FeaturedNews.tsx
> +}
The featured news should be a component/be able to take information from somewhere else rather than have it hardcoded, pretty minor thing.

2023-06-10 14:55 UTC, FemboyDeveloper requested changes
Very minor changes requested, overall looks great! Good job neo!

2023-06-10 14:55 UTC, FemboyDeveloper commented on src/pages/news/index.tsx
> +import { v4 as uuidv4 } from "uuid";
are we using uuids here?

2023-06-10 16:33 UTC, leekahung commented on src/frontend/components/news/FeaturedNews.tsx
> +}
> The featured news should be a component/be able to take information from somewhere else rather than have it hardcoded, pretty minor thing.

The hard-coded is just temporary, so it should be okay for the time being.

2023-06-10 16:35 UTC, leekahung commented on src/pages/news/index.tsx
> +import { v4 as uuidv4 } from "uuid";
As mentioned in the OP, the uuid is a temporary thing that would be replaced  once we're able to generate the keys from the backend.

2023-06-11 00:40 UTC, FemboyDeveloper commented on src/frontend/components/news/FeaturedNews.tsx
> +}
yeah I can accept that, we can change it later once we have some "realer" data lol

2023-06-11 00:42 UTC, merged