Basic Authentication
WarsWorld/WarsWorld pull request #195
Opened 2023-11-15 16:17 UTC by cliveglitch

# Authentication Pull Request
I think I got a lot of progress with the authentication, and I wanted to receive some feedback about what I have.

## Features:
- Login/Signup modal.
- You can Login or Signup with credentials.
- You can Login or Signup with Discord, Google and GitHub providers if you fill the clientId and secret in the .env file for each provider.
- If you create an account by any means, like first login in with a provider or signing up, next auth will create a default player with the name of the user.
- The front end should tell you why you couldn't login or signup if you made a mistake, like wrong user or password, validations, if there is already a user with that email, etc.
- "your-games" will always default to the logged in user's first player.
- You can create games with any new user.
- Protected Page wrapper that will redirect you to the login page if you aren't logged in, example the your-games page.
- Passwords are saved as salted hashes with bcrypt.

## Does not have:
- Sessions.
- Forgot password functionality.
- Role based authorization.

![image](https://github.com/WarsWorld/WarsWorld/assets/56766746/496ca626-c529-43d0-8013-9f4d5ee4a400)
![image](https://github.com/WarsWorld/WarsWorld/assets/56766746/550465fc-71ec-4890-a310-9fc3b2448925)
![image](https://github.com/WarsWorld/WarsWorld/assets/56766746/d9db9491-49f2-4e39-9047-f7de4299e6ae)
![image](https://github.com/WarsWorld/WarsWorld/assets/56766746/27e0e794-6d4b-4fd8-a9f5-500d2c350419)
![image](https://github.com/WarsWorld/WarsWorld/assets/56766746/2a15c8a0-88ba-4330-886d-3db9341162d6)

2023-11-16 16:36 UTC, FunctionDJ requested changes

2023-11-16 16:36 UTC, FunctionDJ commented on next.config.js
> +    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
why only this one? shouldn't next auth read the environment variables regardless?

2023-11-16 16:36 UTC, FunctionDJ commented on prisma/schema.prisma
> +model Account {
if a user uses both discord and email to login, they will have 2 accounts but 1 user on the DB, right?
how would you match them up?

2023-11-16 16:36 UTC, FunctionDJ commented on prisma/schema.prisma
> +  @@unique([provider, providerAccountId])
intuitively, i'd say the unique should be on `[provider, userId]`, no? and then do we even need the `id` anymore when these entrys can and need to be idenfitied by those two properties/columns?

2023-11-16 16:36 UTC, FunctionDJ commented on prisma/schema.prisma
> +  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)
please explain. to me this looks dangerous and would attempt to delete the user when the player gets deleted. or is it the other way around?

2023-11-16 16:36 UTC, FunctionDJ commented on src/frontend/context/players.tsx
> +  const ownedPlayers = user?.ownedPlayers;
have you implemented a "select default player" mechanic like the removed comment said on L25?

2023-11-16 16:36 UTC, FunctionDJ commented on src/pages/api/WarsWorldAdapter.ts
> +export default function WarsWorldAdapter(p: PrismaClient): Adapter {
can you please explain how this works and why it needs an adapter? (basically, pls explain next-auth lol sorry)

2023-11-16 16:36 UTC, FunctionDJ commented on src/pages/api/authOptions.ts
> +      clientId: process.env.GITHUB_CLIENT_ID as string,
how does this handle when you don't specify the necessary environment variables? will there be errors? does the login option still show up?

2023-11-16 16:36 UTC, FunctionDJ commented on src/pages/api/jwt.ts
> +export default async function handler(
i'd prefer not using `default` to incentivise using the actual name of this function, which probably should be something other than `handler`. or if it's truly just an example, the file name should be different.

2023-11-16 16:36 UTC, FunctionDJ commented on src/pages/api/jwt.ts
> +  // If you don't have the NEXTAUTH_SECRET environment variable set,
when would this case come up?

2023-11-16 16:36 UTC, FunctionDJ commented on src/server/hashPassword.ts
> +export default async function hashPassword(password: string) {
no `default` pls

2023-11-16 16:36 UTC, FunctionDJ commented on src/server/routers/match/create.ts
> +  .input(withPlayerNameSchema)
these schemas appear to be used only once, so it's not useful to extract them into reusable variables yet. also you're extending one schema and then using a second `.input` for another one, kind mix-and-matching. i think the mapId, selectedCO and playerName can just be a part of a single inline schema in this case.

2023-11-16 16:36 UTC, FunctionDJ commented on src/server/schemas/auth.ts
> +  password: z.string().min(4).max(20),
we *can* add better password validation here, but i think it's simpler to just do that in the procedure layer. also i think the range should be something more like `8-40`.

2023-11-16 16:36 UTC, FunctionDJ commented on src/server/schemas/auth.ts
> +  confirmPassword: z.string().min(4).max(20),
`confirm`? on the backend, this would just be `password` to us. the confirm part is only frontend.

2023-11-16 16:36 UTC, FunctionDJ commented on src/server/schemas/auth.ts
> +export type ILogin = z.infer<typeof loginSchema>;
unless other types have been prefixed with `I`, it'd be consistent to remove them.

2023-11-16 16:36 UTC, FunctionDJ commented on src/server/trpc/middleware/player.ts
> +    const ownedPlayers = await getProductionModeUserPlayers(ctx.session);
so there's no getDevModePlayers anymore? if the function handles this internally, the name should be updated. otherwise, dev mode players are missing now.

2023-11-16 16:36 UTC, FunctionDJ commented on src/server/trpc/trpc-init.ts
> +            ? error.cause.flatten()
i know this is from the trpc docs but some de-nesting could improve readability here.

2023-11-16 18:13 UTC, cliveglitch commented on src/pages/api/authOptions.ts
> +      clientId: process.env.GITHUB_CLIENT_ID as string,
You simply cannot log in with those providers. You don't need to specify them all, if you want to try to log in with GitHub, just fill GitHub's env variables, and if you want to log in with email and password you don't need to fill any.

2023-11-16 18:36 UTC, cliveglitch commented on prisma/schema.prisma
> +model Account {
Next Auth looks for the tables called User and Account to login and signup a user and that's why the naming, Accounts are all the providers the user have tied, like Discord, GitHub and Google. 

For now there is no functionality to bind two emails to the same user at the moment, that means if you try to sign up with email/password and then you try to login for the first time with discord it will throw an error. Also email signup is not made into an account, it just fills the password so the user can login with a password.

In short, you sign up as one user, that user can have cero to many accounts (like discord), and that user can have 1 to many players, players being the entities that can play the game.

2023-11-16 18:40 UTC, cliveglitch commented on prisma/schema.prisma
> +  @@unique([provider, providerAccountId])
I've took this schema from NextAuth's documentation: https://next-auth.js.org/v3/adapters/prisma
And I think it is what NextAuth expects for this to work.

2023-11-16 18:42 UTC, cliveglitch commented on prisma/schema.prisma
> +  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)
Deletes the player when the user is deleted, I just put that there to make it more convenient to delete users and test the functionality, is it fine?

2023-11-16 18:43 UTC, cliveglitch commented on src/frontend/context/players.tsx
> +  const ownedPlayers = user?.ownedPlayers;
Yes, even if you create a new User, when you enter the page the first player will be selected.

2023-11-16 19:06 UTC, cliveglitch commented on next.config.js
> +    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
I've continued Matthew's work and that is something he left there, it stills works fine without it but I cannot say why it's needed there.

2023-11-16 19:08 UTC, cliveglitch commented on src/pages/api/jwt.ts
> +export default async function handler(
I understand, didn't had that on mind while trying to create my functions, I just added the default to the main function of the file, but I follow you.

2023-11-16 19:16 UTC, cliveglitch commented on src/server/trpc/middleware/player.ts
> +    const ownedPlayers = await getProductionModeUserPlayers(ctx.session);
Ok, change the name, I used only getProductionModeUserPlayers so I can see the players of any new user that doesn't have that prefix.

2023-11-16 23:37 UTC, cliveglitch commented on src/pages/api/jwt.ts
> +  // If you don't have the NEXTAUTH_SECRET environment variable set,
Matthew's file, I think it'd come up with sessions, but for now I plan to leave with sessions in a future PR, so I'm inclined to delete this file.

2023-11-17 00:15 UTC, cliveglitch commented on src/server/routers/match/create.ts
> +  .input(withPlayerNameSchema)
Doesn't seem like the name input is needed in the first place, I think I left it there when trying to show the player's name instead of their Id on those match cards but kinda forgot.

2023-11-17 00:59 UTC, cliveglitch commented on src/server/schemas/auth.ts
> +  confirmPassword: z.string().min(4).max(20),
hehe I was kinda playing with zod and what I can do, the latest commit should move the confirm check to the front.

2023-11-17 01:11 UTC, cliveglitch commented on src/server/trpc/trpc-init.ts
> +            ? error.cause.flatten()
mmm... how would you de-nest it?

2023-11-17 01:13 UTC, cliveglitch commented on src/server/hashPassword.ts
> +export default async function hashPassword(password: string) {
Done

2023-11-17 01:13 UTC, cliveglitch commented on src/server/schemas/auth.ts
> +export type ILogin = z.infer<typeof loginSchema>;
Done

2023-11-17 09:02 UTC, FunctionDJ commented on next.config.js
> +    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
then it should be removed.

2023-11-17 09:09 UTC, FunctionDJ commented on prisma/schema.prisma
> +  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)
it's probably fine, but if a user gets deleted, we need to do cleanups regardless.
players can have clan relationships, which need to be resolved. the "ownedClans" one can't be cascade-deleted i think.
i'm not sure if we should use cascade deletion or just do everything manually because we can't fully "automate" it anyway.

2023-11-17 09:12 UTC, FunctionDJ commented on src/frontend/components/auth/SignupForm.tsx
> +  const [doPasswordsMatch, setDoPasswordsMatch] = useState(true);
i don't think state is needed. just do `passwordsMatch = signupData.password === signupData.confirmPassword`

2023-11-17 09:21 UTC, FunctionDJ commented on src/pages/api/authOptions.ts
> +      clientId: process.env.GITHUB_CLIENT_ID as string,
i've tested it and the buttons show up and i think clicking them will start the oauth flow which will immediately just redirect to the application (like a refresh) when these environment variables are are missing/invalid.

i think it would be a good idea if we made this more explicit in the GUI (e.g. for new developers) where the buttons are greyed out or just removed if the credentials are not set.

the latter might be easy to achieve by padding the providers conditionally like we've done in the past at points.
what do you think?

2023-11-17 09:25 UTC, FunctionDJ commented on src/server/trpc/trpc-init.ts
> +            ? error.cause.flatten()
i think pulling the value of `zodError` into a variable makes sense.

2023-11-17 09:27 UTC, FunctionDJ commented on src/pages/api/WarsWorldAdapter.ts
> +export default function WarsWorldAdapter(p: PrismaClient): Adapter {
so when someone uses email/password to sign up, they don't get a default player, right?
can we do something about that?

2023-11-17 17:41 UTC, cliveglitch commented on src/pages/api/WarsWorldAdapter.ts
> +export default function WarsWorldAdapter(p: PrismaClient): Adapter {
They do, and I already have that done, you just need to add that logic separately.
NextAuth is not so keen with credentials login with password, so they design it to take more effort to set it up purposefully.

2023-11-17 17:42 UTC, cliveglitch commented on src/pages/api/authOptions.ts
> +      clientId: process.env.GITHUB_CLIENT_ID as string,
sounds like a good idea, I'm gonna work on it, later I'll tell you when it's done.

2023-11-17 17:44 UTC, cliveglitch commented on prisma/schema.prisma
> +  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)
would need some time to investigate this, for now I got this for testing purposes so we could change if it has no real use.

2023-11-18 02:59 UTC, cliveglitch commented on prisma/schema.prisma
> +  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)
I opted to remove the the onCascade deletion for now, if I can find a way to automatically delete a user completely then we can discuss that later.

2023-11-18 03:02 UTC, cliveglitch commented on src/pages/api/authOptions.ts
> +      clientId: process.env.GITHUB_CLIENT_ID as string,
Done, it now greys out the buttons when you don't have the necessary env variables for that provider. 
In this example I don't have the env for Google's provider.
![image](https://github.com/WarsWorld/WarsWorld/assets/56766746/14eea864-fde8-4d1f-83bc-16ce7f070cc3)

2023-11-18 03:02 UTC, cliveglitch commented on src/server/trpc/trpc-init.ts
> +            ? error.cause.flatten()
Done

2023-11-18 03:02 UTC, cliveglitch commented on src/frontend/components/auth/SignupForm.tsx
> +  const [doPasswordsMatch, setDoPasswordsMatch] = useState(true);
Done

2023-11-20 21:30 UTC, FunctionDJ requested changes

2023-11-20 21:30 UTC, FunctionDJ commented on src/frontend/components/modals/LoginSignupModal.tsx
> +    LiteralUnion<BuiltInProviderType, string>,
maybe this type expression can be simplified with something like
```ts
Awaited<ReturnType<typeof getProviders>>
```
but i'll leave this up to you if it's better or not (if it works)

2023-11-20 21:30 UTC, FunctionDJ commented on src/frontend/components/modals/LoginSignupModal.tsx
> +  const renderProviders = () =>
inline components should be avoided because of re-renders (and it would also break hooks/state). just make `currentProviders` a prop. you don't need to turn `possibleProviders` into a prop since it can live outside of components anyway.

2023-11-20 21:30 UTC, FunctionDJ commented on src/pages/api/authOptions.ts
> +      const creds = await loginSchema.parseAsync({
this code could be simplified by making the submitted data fit to the loginSchema or vice versa.
then you could do `const { username, password } = loginSchema.safeParse(credentials)`
([don't use `async` unless the schema uses async refiners etc.](https://github.com/colinhacks/zod#parseasync))
(also i think [.strict()](https://github.com/colinhacks/zod#strict) would be a good idea here to ban needless properties which could indicate issues, up to you whether to apply it here when used or to put it on `loginSchema`'s definition directly)

2023-11-20 21:30 UTC, FunctionDJ commented on src/pages/api/authOptions.ts
> +      if (doPasswordsMatch) {
i think code makes more sense with early-returns in "failure cases", related to the "fail fast" principle.
in practise, that'd mean `if (!doPasswordsMatch) { return null; } ...`

2023-11-20 21:30 UTC, FunctionDJ commented on src/pages/api/authOptions.ts
> +  debug: true,
maybe something like `debug: process.env.NODE_ENV === "dev"` ?
idk which env vars are currently available to check for development.
maybe just `console.log(process.env)` and see if something's in there.

2023-11-21 16:35 UTC, cliveglitch commented on src/frontend/components/modals/LoginSignupModal.tsx
> +    const setProviders = async () => {
Much simpler.

2023-11-21 16:35 UTC, cliveglitch commented on src/frontend/components/modals/LoginSignupModal.tsx
> +    LiteralUnion<BuiltInProviderType, string>,
It works, so it's worth it to change it.

2023-11-21 16:36 UTC, cliveglitch commented on src/pages/api/authOptions.ts
> +  debug: true,
Done.

2023-11-21 19:51 UTC, cliveglitch commented on src/pages/api/authOptions.ts
> +      const creds = await loginSchema.parseAsync({
Decided to leave out the .strict(), but everything else is done.

2023-11-21 19:54 UTC, cliveglitch commented on src/frontend/components/modals/LoginSignupModal.tsx
> +  const renderProviders = () =>
I've just put back the map into the jsx

2023-11-21 19:56 UTC, cliveglitch commented on src/frontend/components/modals/LoginSignupModal.tsx
> +  const posibleProviders = ["github", "discord", "google"];
Done.

2023-11-21 21:40 UTC, cliveglitch commented on src/frontend/components/auth/SignupForm.tsx
> +    signupData.confirmPassword === "";
I think it's a misunderstanding, I've changed the code a bit to make it more obvious, but the purpose of that conditional is when to `show` an error, the logic is, when the passwords do not match and there is at least a character on both the inputs then it will show the error.
It's to not bother the user with a "Passwords do not match message when they are typing the first password".

2023-11-21 21:55 UTC, cliveglitch commented on src/frontend/components/auth/SignupForm.tsx
> +    if (signupData.confirmPassword !== signupData.password) {
You can submit when passwords do not match, there is no code that stops the user not to submit until that point.
The code on the review above was to show the error.

2023-11-23 10:58 UTC, FunctionDJ commented on src/frontend/components/auth/SignupForm.tsx
> +    signupData.confirmPassword === "";
Ah, i get it now. Please change the variable to something like
```ts
const showPasswordsDoNotMatch = signupData.password !== "" && signupData.confirmPassword !== "" && signupData.password !== signupData.confirmPassword
```
This makes the logic and the intent behind this code much easier to understand, because the variable isn't exclusively about whether the passwords match, but also if it makes sense to show a "passwords don't match" hint.

2023-11-23 10:59 UTC, FunctionDJ commented on src/frontend/components/auth/SignupForm.tsx
> +    if (signupData.confirmPassword !== signupData.password) {
Why not disable the submit button when passwords don't match instead?

2023-11-23 11:04 UTC, FunctionDJ commented on src/frontend/components/modals/LoginSignupModal.tsx
> +  const renderProviders = () =>
yes, that's fine.

2023-11-23 11:12 UTC, FunctionDJ commented on src/pages/api/authOptions.ts
> +      } as User;
What's up with this type override?

2023-11-23 16:12 UTC, cliveglitch commented on src/frontend/components/auth/SignupForm.tsx
> +    if (signupData.confirmPassword !== signupData.password) {
Kinda does the same I suppose, you just get rejected after you click it. I've change it no problem, and also added so you cannot press the button if you have empty fields because it doesn't make sense to disable it only with the passwords.

2023-11-23 16:13 UTC, cliveglitch commented on src/frontend/components/auth/SignupForm.tsx
> +    signupData.confirmPassword === "";
Done.

2023-11-23 16:19 UTC, cliveglitch commented on src/pages/api/authOptions.ts
> +      } as User;
You get this error otherwise:
![image](https://github.com/WarsWorld/WarsWorld/assets/56766746/d7fa7664-cb4e-4588-bc06-5e0dbd897459)

You can add the id to the object (I did that on the last commit), and it works the same.

2023-11-23 16:54 UTC, FunctionDJ approved these changes

2023-12-01 23:06 UTC, merged