Migrating layout from demo 2
WarsWorld/WarsWorld pull request #83
Opened 2023-04-20 02:36 UTC by leekahung

Same as before in PR #82, but I moved the branch from my fork to the main repo.

Although there are changes related to the mapGrid, I think we can at least push into the main branch the changes with regards to a Layout component (with Header/Navbar and Footer). 

Link/Images for navbar could be altered depending on what we would want later on.

2023-04-20 03:13 UTC, leekahung commented
Going to swap to tailwind after potential merge now that it's added to the project.

2023-04-20 10:29 UTC, leekahung commented
Implementing Match Page idea to PR.

![match_page_layout_idea](https://user-images.githubusercontent.com/14917816/233303862-f84cf200-601f-4be6-8a80-81dc33f35226.png)

As you can see below, the smallest I could get it to go at this moment with the existing design is 330px by 722px. Things starts breaking after that. But this is only optimized for the Match Page.

![Screen Shot 2023-04-20 at 3 21 36](https://user-images.githubusercontent.com/14917816/233339032-3f8e7188-f0f1-4428-83a4-913991118a9e.png)
![Screen Shot 2023-04-20 at 3 22 34](https://user-images.githubusercontent.com/14917816/233339064-32be1b26-0185-438b-a9c1-962fd785f5b4.png)
![Screen Shot 2023-04-20 at 3 23 27](https://user-images.githubusercontent.com/14917816/233339109-57e1b399-6e37-4a56-bfe1-9412dec0d386.png)
![Screen Shot 2023-04-20 at 3 23 45](https://user-images.githubusercontent.com/14917816/233339203-cd0eb32f-4cc5-4c80-8aac-3cf93c9cb30e.png)
![Screen Shot 2023-04-20 at 3 24 06](https://user-images.githubusercontent.com/14917816/233339228-de69f864-63ad-4061-816c-87e2cccf7bb9.png)
![Screen Shot 2023-04-20 at 3 24 37](https://user-images.githubusercontent.com/14917816/233339240-394bff8d-ec85-4061-8e72-856d17326e0e.png)

2023-04-20 17:17 UTC, FemboyDeveloper commented
@WesKrug is this ready for merging?

2023-04-20 17:41 UTC, FemboyDeveloper commented
I just checked this out, looks pretty nice overall! Its a nice skeleton!

2023-04-21 20:32 UTC, WesKrug approved these changes

2023-04-21 20:32 UTC, WesKrug commented on src/components/Footer.tsx
> +        <img className="footerLogo" src={rLogoPath} alt="Reddit Logo" />
Any reason you're not just using @h-8 for 32px here?

2023-04-21 20:32 UTC, WesKrug commented on src/styles/template/layout.scss
> +  footer {
This appears to be unused

2023-04-21 20:32 UTC, WesKrug commented on src/pages/home.tsx
> +      <div className="@rounded-lg @bg-black/70 @center @p-8 @max-w-3xl isProgress">
Super nitpicky. should be `inProgress`, not `isProgress`
```suggestion
      <div className="@rounded-lg @bg-black/70 @center @p-8 @max-w-3xl inProgress">
```

2023-04-21 20:32 UTC, WesKrug commented on src/styles/template/layout.scss
> +  .isProgress {
same nitpick
```suggestion
  .inProgress {
```

2023-04-21 20:36 UTC, leekahung commented
Player Box updates looks like this. Last image shows a working burger menu for mobile.

![Screen Shot 2023-04-21 at 13 35 50](https://user-images.githubusercontent.com/14917816/233730025-70e90036-87b2-4a4e-8dad-7164a8a11936.png)
![Screen Shot 2023-04-21 at 13 28 03](https://user-images.githubusercontent.com/14917816/233729721-0e6290a9-f7c8-4357-aaa5-7edfd4fea31e.png)
![Screen Shot 2023-04-21 at 13 28 25](https://user-images.githubusercontent.com/14917816/233729743-f3ca27fe-f012-485d-99e2-a3b2b26d44be.png)
![Screen Shot 2023-04-21 at 13 33 26](https://user-images.githubusercontent.com/14917816/233729769-f2405dbc-6252-47ec-a5e5-0ac93ce1c76d.png)

2023-04-21 20:42 UTC, leekahung commented on src/pages/home.tsx
> +      <div className="@rounded-lg @bg-black/70 @center @p-8 @max-w-3xl isProgress">
Got it, getting this fixed. It appears I've missed the className in the spreadsheet as well (Line 33 of layout.scss). I'll change it there as well.

2023-04-21 20:42 UTC, leekahung commented on src/styles/template/layout.scss
> +  .isProgress {
Fixed.

2023-04-21 20:45 UTC, leekahung commented on src/components/Footer.tsx
> +        <img className="footerLogo" src={rLogoPath} alt="Reddit Logo" />
Good spot. No reason in particular. I should just use @h-8 from tailwind.

2023-04-21 20:46 UTC, leekahung commented on src/styles/template/layout.scss
> +  footer {
It's being used for footer height: 160px

2023-04-21 21:17 UTC, leekahung reviewed
Minor check going through every file. Please review.

2023-04-21 21:17 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +              <span>{playerInMatch.username}</span>
This is just a singular element now with just playerUsername. No need to wrap in div.

2023-04-21 21:17 UTC, leekahung commented on src/styles/grid/global.scss
> +          display: flex;
Can migrate some props from all classes under playerBox (this class is a good example)

2023-04-21 21:17 UTC, leekahung commented on src/styles/grid/global.scss
> +    flex-direction: column;
Redundany, flex-direction never changes for gameInnerBox

2023-04-21 21:19 UTC, leekahung commented on src/styles/grid/global.scss
> +  z-index: 20;
Resolved redundancy

2023-04-21 21:21 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +              <span>{playerInMatch.username}</span>
Added tailwind classes for playerUsername, playerIngameExp, playerIngameInfo, gameTime, and others inside playerBox

2023-04-21 21:21 UTC, leekahung commented on src/styles/grid/global.scss
> +          display: flex;
Resolved, have changed props

2023-04-21 21:21 UTC, leekahung commented on src/styles/grid/global.scss
> +    flex-direction: column;
Lines removed.

2023-04-22 20:39 UTC, FemboyDeveloper commented
@leekahung is this ready for merging?

2023-04-22 21:31 UTC, FunctionDJ requested changes
interesting stuff. some of my comments are picky and are more about learning about the decisions behind the code rather than the actual code, please excuse that.

2023-04-22 21:31 UTC, FunctionDJ commented on src/components/layout.tsx
> +export default function Layout({ addFooter, children }: Props) {
please use named exports when possible (next pages must use default exports).
they are better for refactoring. more info: https://stackoverflow.com/a/33307487

2023-04-22 21:31 UTC, FunctionDJ commented on src/pages/home.tsx
pages should not be used as components in other files (`index.tsx`). it should either be a page or a component (components folder) which then doesn't get rendered as it's own page.
as it is right now we'd have `/` and `/home` (two pages)  with the same or similar content.

2023-04-22 21:31 UTC, FunctionDJ commented on src/pages/index.tsx
> +  const documentHeight = () => {
see my other comment about javascript-less responsive design.
but aside from that `documentHeight` would be a good name for a value but not for a function. if we kept this function, `updateDocumentHeightCSSProperty` or something similar would be better.

2023-04-22 21:31 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
> +interface INationColorGradients {
both of these interfaces express the same as `Record<string, string>`

2023-04-22 21:31 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
> +  const nationColors: INationColors = {
objects that don't depend on component data should be created outside of components in order not to trigger unnecessary re-renders.

2023-04-22 21:31 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
> +              playerTurn ? null : 'isNotPlayerTurn'
`null` gets stringified to `"null"`, not to empty string `""`!
so please use empty string :)

2023-04-22 21:31 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
> +  const [turn, setTurn] = useState({ player1: true, player2: false });
this object reference creation on-render can be unsafe in certain conditions. if you must use objects in this way and they are independent of components state like in this case, move them outside the component so the reference stays the same.

2023-04-22 21:31 UTC, FunctionDJ commented on src/styles/grid/global.scss
> +  .gameTime {
you wouldn't want to re-use this class name `.gameTime` for anything else, so in my opinion these styles shouldn't be restricted to children of `.gameInnerBox`. the nesting suggests that the class name `.gameTime` might get different styles when used as a child of another specific class or id.

2023-04-22 21:31 UTC, FunctionDJ commented on src/styles/match.module.css
> +    gap: 10px;
thoughts about using `em` or `rem` over pixels?

2023-04-22 21:31 UTC, FunctionDJ commented on src/styles/template/layout.scss
> +  height: var(--doc-height);
idk about this one chief

2023-04-22 21:31 UTC, FunctionDJ commented on src/styles/template/layout.scss
> +  overflow: hidden;
this is a hack to hide scrollbars in this case because an element can be too big.
it'd be better to fix the issue causing elements to grow too large instead of patching it this way which can cause scrolling issues.

2023-04-22 21:31 UTC, FunctionDJ commented on src/styles/template/layout.scss
> +  main::-webkit-scrollbar {
hax?

2023-04-22 21:31 UTC, FunctionDJ commented on src/utils/useMediaQuery.ts
> +    if (media.matches !== matches) {
this if is effectively a no-op because the state contains a primitive value.

2023-04-22 21:48 UTC, leekahung commented
@FemboyDeveloper Yeah, I think we're ready for mergin. Lemme go through the feedback from @FunctionDJ first and see what still need to be updated or modified.

2023-04-22 21:55 UTC, leekahung commented on .vscode/settings.json
> -  "editor.defaultFormatter": "rvest.vs-code-prettier-eslint",
It appears to be a VSCode thing. I didn't have the extension, so it originally showed as a value not accepted.

Found the extension and installed it locally. I should be able to turn this back on. and remove the only format with just prettier.

2023-04-22 21:55 UTC, leekahung commented on .vscode/settings.json
> +    "editor.defaultFormatter": "esbenp.prettier-vscode"
Found where the issue was. Should be able to revert back to the original settings.

2023-04-22 21:57 UTC, leekahung commented on src/components/Footer.tsx
> +        All images are copyright their respective owners.
Fixed "All images are copyright their respective owners" to "All images are copyright of their respective owners"

2023-04-22 22:21 UTC, leekahung commented on public/img/layout/burgerMenu.png
Originally, I had an icon lying around so I wanted to use it. Other than that, there shouldn't been any issues swapping to an HTML-based one.

I'll change it.

2023-04-22 22:29 UTC, leekahung commented on src/components/IngameInfo.tsx
> +  value: string | number;
Yes, "value" should be sufficient for mocking. We could name it "ingameStat" for future-proofing. That should be a better name.

As for the typing, I don't really know what type of data that's going to be passed into it yet, just that it might be a number (i.e. income amount, number of units, etc.) or a time (i.e. player turn timer).

I could use a Date for typing the time, but it's being passed as a string in the mock, so the typing is left like that.

2023-04-22 22:34 UTC, leekahung commented on src/styles/match.module.css
> +    gap: 10px;
That was the initial idea, which was why gap for .match is set in rem. But It's difficult to maintain a "min-gap" that takes into account media queries. There are many times where rem makes the component stick past the screen because the screen was not small enough in either the vertical or horizontal directions.

2023-04-22 22:45 UTC, leekahung commented on src/styles/template/layout.scss
> +  height: var(--doc-height);
I mean, I could always use dvh. But I don't think dvh is supported by FireFox? [https://caniuse.com/?search=dvh](https://caniuse.com/?search=dvh)

I need a fallback regardless. [see this stackoverflow](https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser#:~:text=Yes%2C%20100vh%20is%20100%25%20of,only%20to%20this%20parent%20height).)

2023-04-22 22:47 UTC, leekahung commented on src/styles/template/layout.scss
> +  overflow: hidden;
No, I want to hide the scroll bar completely for a better experience.

2023-04-22 22:47 UTC, leekahung commented on src/styles/template/layout.scss
> +  main::-webkit-scrollbar {
No, I just want to hide the scroll bar completely.

2023-04-22 22:48 UTC, leekahung commented on src/utils/useMediaQuery.ts
> +    if (media.matches !== matches) {
I'm not quite understanding this feedback?

2023-04-22 22:49 UTC, leekahung commented on src/components/NavItem.tsx
> +  const query500 = useMediaQuery('(max-width: 500px)');
No, it's not required for tailwind from what I've saw in the docs. But we didn't not set up our existing tailwind config to handle responsive breakpoints, so I need a custom hook for now.

2023-04-22 22:58 UTC, leekahung commented on src/components/Navbar.tsx
> +          <img className="@flex headerLogo" src={awLogoPath} alt="AW Logo" />
Could switch to it. Didn't now about this component in NextJS.

2023-04-22 23:00 UTC, leekahung commented on src/components/layout.tsx
> +  addFooter?: boolean;
Can be done. Changing prop from addFooter to just footer

2023-04-22 23:08 UTC, leekahung commented on src/components/layout.tsx
> +  if (typeof document !== 'undefined') {
Yes, it's a check. I can swap to window instead of document.

2023-04-22 23:12 UTC, leekahung commented on src/components/layout.tsx
> +        document.documentElement.style.setProperty(
Usually, it's pretty easy to select from :root for dynamically adjusting dynamic CSS properties outside of SASS [see MDN link](https://developer.mozilla.org/en-US/docs/Web/CSS/:root)

However, Next seems to be doing its own thing?

2023-04-22 23:19 UTC, leekahung commented on src/pages/_app.tsx
> +import '../styles/grid/global.scss';
Moved both SASS files into global.css (now renamed global.scss) for importing by using @use

2023-04-22 23:19 UTC, leekahung commented on src/components/layout.tsx
> +      {addFooter ? <Footer /> : null}
Got this changed

2023-04-22 23:21 UTC, leekahung commented on src/pages/home.tsx
> +        <link rel="icon" href="/favicon.ico" />
Moving this to _app.tsx

2023-04-22 23:23 UTC, leekahung commented on src/pages/home.tsx
> +          <a href={'https://github.com/WarsWorld/WarsWorld/issues'}>
You are right.

This was a very silly mistake on my part. I didn't know why I use that instead of a string, lol.

2023-04-22 23:25 UTC, leekahung commented on src/pages/howtoplay/index.tsx
> +export default function howToPlayPage() {
I didn't know NextJS pages are React components. Noted and changed it to PascalCase.

2023-04-22 23:29 UTC, leekahung commented on src/components/layout.tsx
> +export default function Layout({ addFooter, children }: Props) {
Changed Layout as a named export. I should change existing components to named exports as well.

2023-04-22 23:36 UTC, leekahung commented on src/pages/home.tsx
Should I move home and about in their own folder in pages? I'm a little confused over this feedback.

2023-04-22 23:38 UTC, leekahung commented on src/pages/index.tsx
> +  const documentHeight = () => {
Noted, I'll use updateDocumentHeightCSSProperty as the function name.

2023-04-22 23:40 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +interface INationColorGradients {
I'll just keep INationColors instead of having both.

2023-04-22 23:41 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +  const nationColors: INationColors = {
Remove console.log from Line 37?

2023-04-22 23:42 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +              playerTurn ? null : 'isNotPlayerTurn'
I've noticed that and had been swapping them out. I guess I missed this one. Changing it to an empty string.

2023-04-22 23:45 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +  const [turn, setTurn] = useState({ player1: true, player2: false });
I'm a little confused on this feedback? Do you mean to lift this to a global state?

2023-04-22 23:54 UTC, leekahung commented on src/styles/grid/global.scss
> +  .gameTime {
Moving .gameTime outside of .gameInnerBox

2023-04-22 23:55 UTC, leekahung commented on src/styles/template/layout.scss
> +  main::-webkit-scrollbar {
No, just want to hide the scroll bar as intended.

2023-04-23 00:37 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
> +interface INationColorGradients {
actually that type doesn't do anything because it only gets used once and doesn't convey any meaningful information. i suggest to just remove it. typescript will still infer the object shape.

2023-04-23 00:40 UTC, FunctionDJ commented on src/utils/useMediaQuery.ts
> +    if (media.matches !== matches) {
when you set a state, react will only re-render if the new value is a different primitive value or a different object reference.
with this `if` you're preventing the case where you would set the same primitive value that's currently set, but that wouldn't cause react to re-render.
so you can and should remove this `if` because it effectively makes no difference.

2023-04-23 01:00 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +  const nationColors: INationColors = {
Removed nationsColors

2023-04-23 01:01 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +  const [turn, setTurn] = useState({ player1: true, player2: false });
It's just there for mocking the pass turn functionality. We can leave it for now.

2023-04-23 01:18 UTC, leekahung commented on src/utils/useMediaQuery.ts
> +    if (media.matches !== matches) {
I see what you mean.

It does need the condition though for the listener to pick up the media query, so I moved the if statement inside listener, replacing what it was there originally.

2023-04-23 04:22 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +interface INationColorGradients {
Oh! I get was you mean now.

Okay, I'll remove the interface in favor of a generic Record.

2023-04-23 05:03 UTC, leekahung commented on src/styles/template/layout.scss
> +  height: var(--doc-height);
Going to fall back on vh. If vh becomes insufficient as a fall back, we can re-consider --doc-height. For now, I'll leave them out.

2023-04-23 06:25 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +  const [turn, setTurn] = useState({ player1: true, player2: false });
Actually, it doesn't even have to be an object with booleans. Thinking about it again, I should just straight up use a boolean.

If I do const [turn, setTurn] = useState(true)

I should just pass turn as a prop to player 1 and !turn to player 2.

Damn, even if it's just a mock, I probably over-complicated the problem. Lol.

2023-04-23 19:23 UTC, FunctionDJ requested changes

2023-04-23 19:23 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
>  interface INationColors {
if you must use a custom type name, at least do `type INationColors = Record<string, string>`... or like just get rid of the type because it's shape doesn't transfer any useful information.

2023-04-23 19:23 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
> +  const nationColorGradients: INationColors = {
this object should live outside the react component.

2023-04-23 19:25 UTC, FunctionDJ requested changes

2023-04-23 19:25 UTC, FunctionDJ commented on public/img/layout/burgerMenu.png
please remove if unused

2023-04-23 19:29 UTC, FunctionDJ commented on src/components/layout.tsx
> +        document.documentElement.style.setProperty(
using `:root` in CSS is fine, but *writing* to the DOM using the DOM API from inside react for a media query workaround... that's what's surprising me.

2023-04-23 19:33 UTC, leekahung commented on src/components/NavItem.tsx
> +  const query500 = useMediaQuery('(max-width: 500px)');
Yeah, I can do that. I'll add the TODO comment around

2023-04-23 19:36 UTC, leekahung commented on src/pages/_app.tsx
> +// import '../styles/grid/global.scss';
This has been updated in recent commits

2023-04-23 19:40 UTC, leekahung commented on public/img/layout/burgerMenu.png
Removing unused png.

2023-04-23 19:45 UTC, leekahung commented on src/pages/_app.tsx
> +// import '../styles/grid/global.scss';
Comment has already been removed in the updated file:

```
import '../styles/globals.scss';
import type { Session } from 'next-auth';
```

2023-04-23 19:46 UTC, leekahung commented on src/components/layout.tsx
> +      {footer ? <Footer /> : null}
Changing this from ternary to logical and

2023-04-23 19:51 UTC, leekahung commented on src/pages/match/[matchId].tsx
>  interface INationColors {
Record<string, string> is in use in the updated version, original Interface has already been removed:

```
interface Props {
  playerTurn: boolean;
  playerInMatch: PlayerInMatch;
}

const PlayerBox = ({ playerTurn, playerInMatch: playerInMatch }: Props) => {
  const time = new Date(0);
  time.setSeconds(playerInMatch.timePlayed ?? 1);

  const nationColorGradients: Record<string, string> = {
    blue: '@bg-gradient-to-l @from-blue-400',
    orange: '@bg-gradient-to-l @from-orange-400',
    green: '@bg-gradient-to-l @from-green-400',
    yellow: '@bg-gradient-to-l @from-yellow-400',
  };
```

2023-04-23 19:52 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
> +  const [turn, setTurn] = useState({ player1: true, player2: false });
for mock you could do `useState<"player1" | "player">("player1")`

2023-04-23 19:52 UTC, FunctionDJ commented on src/styles/template/layout.scss
> +  height: var(--doc-height);
i meant the two height properties.

2023-04-23 19:52 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +  const nationColorGradients: INationColors = {
INationColors and INationColorGradients has been removed in favor of Record<string, string> (see Line 31 of the latest commit)

2023-04-23 19:53 UTC, FunctionDJ commented on src/styles/template/layout.scss
> +  main::-webkit-scrollbar {
why is there a scrollbar?

2023-04-23 19:56 UTC, leekahung commented on src/utils/useMediaQuery.ts
> +      if (media.matches !== matches) {
Added TODO for when we switch from custom Hook to tailwind media queries.

But I believe you mean just to use setMatches(media.matches) under const media in Line 8?

2023-04-23 20:08 UTC, leekahung commented on src/components/layout.tsx
> +        document.documentElement.style.setProperty(
Is there a way to dynamically change the variable in :root outside of this method? I thought this was normal? For example: [stackoverflow](https://stackoverflow.com/questions/37801882/how-to-change-css-root-color-variables-in-javascript)

2023-04-23 20:10 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +  const [turn, setTurn] = useState({ player1: true, player2: false });
I could use a more complicated state, but I do think for the mock, a simple true/false is enough.

2023-04-23 20:11 UTC, leekahung commented on src/styles/template/layout.scss
> +  overflow: hidden;
Overflow hidden removed in the updated file.

2023-04-23 20:14 UTC, leekahung commented on src/styles/template/layout.scss
> +  main::-webkit-scrollbar {
This is for edge cases like with wide screens, but small device heights like the Google Next Hub. Still needs scrolling for now, but needs to be fixed the future. I'll add a TODO here.

2023-04-23 20:19 UTC, leekahung commented on src/styles/template/layout.scss
> +  height: var(--doc-height);
Oh, this is for CSS fallback.

Since it's CSS, if the property on the bottom fails, it'll always read the top one and if the bottom one doesn't fail, it'll always read the bottom one. It's a safe way to ensure the property is set based on browser compatibility.

2023-04-23 20:49 UTC, leekahung commented on src/components/IngameInfo.tsx
> +  value: string | number;
I've also renamed iconPath as ingameStatIconPath for better clarity

2023-04-23 20:53 UTC, leekahung commented on src/pages/_app.tsx
> +import '../styles/grid/global.scss';
Removing line for the unused SASS files from here

2023-04-23 20:54 UTC, leekahung commented on src/pages/home.tsx
Have moved home.tsx to components and renamed it Home.tsx

2023-04-23 20:55 UTC, leekahung commented on src/pages/index.tsx
> +  const documentHeight = () => {
After thinking about it some more, we can remove this in favor of vh, dvh in css

2023-04-23 20:56 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +  const nationColors: INationColors = {
Removed interface completely in favor of Record

2023-04-23 20:59 UTC, leekahung commented on src/utils/useMediaQuery.ts
> +    if (media.matches !== matches) {
I think I get what you mean now. Dropping conditional completely and just leave the function inside it in line 9

2023-04-24 20:00 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
> +  const nationColorGradients: INationColors = {
it's still not outside the component :)

2023-04-24 20:08 UTC, FunctionDJ approved these changes
there's this one really minor thing left (independent object in react component) but it's not worth dragging this out any longer.
LGTM.

2023-04-24 20:18 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +  const nationColorGradients: INationColors = {
Oh, you meant the nationColorGradient object and not the types/interface! My mistake. I know what to do. I'll leave them outside of this PR for now, but make a note for it.

2023-04-24 21:48 UTC, FemboyDeveloper commented
Just checked it out, absolutely wonderful work, thanks for your extensive help FunctionDJ!

2023-04-24 21:49 UTC, merged