Pull Request Checks
WarsWorld/WarsWorld pull request #91
Opened 2023-04-29 16:23 UTC by onetrickwolf

Setting up GitHub action to run on pushes to main and on pull requests targeting main. Just runs the build to make sure it's not broken and does linting and prettier checks. Eventually we can add testing to this.

I think this is important to get in early so we don't have run away style issues.

- Added [pr-checks.yml](https://github.com/WarsWorld/WarsWorld/compare/main...onetrickwolf:WarsWorld:gh-action-checks#diff-1da7a27709d11ac16eef3de8e46ed10672b7b1d63a790ffbcbd23a94b19efdcb)
- Added [.prettierignore](https://github.com/WarsWorld/WarsWorld/compare/main...onetrickwolf:WarsWorld:gh-action-checks#diff-b640b344ee7f3f03d2a443795a5d0708ef50e2e6e34214109ab2aad13ad6ba98) so we aren't doing prettier checks on build folders etc
- Linting max warnings set to 10 while to give us some room while we are stabilizing the project
- [.nvmrc](https://github.com/WarsWorld/WarsWorld/compare/main...onetrickwolf:WarsWorld:gh-action-checks#diff-2c8effdf840690ccb88c7e21e56148978c6adb2c6926530c58ff0e47a9588b44) added to specify `node 18` for the project
- All other file changes are just prettier fixes to get build to initially pass

2023-04-29 16:29 UTC, FunctionDJ requested changes

2023-04-29 16:29 UTC, FunctionDJ commented on package.json
> +    "prettier": "prettier --check .",
please change name to "lint-prettier" or similar to make obvious that this doesn't do any `--fix` stuff

2023-04-29 16:29 UTC, FunctionDJ commented on package.json
> +    "prettier": "prettier --check .",
actually, maybe just add this to `pnpm lint`

2023-04-29 16:29 UTC, FunctionDJ commented on .gitignore
> +/dist/
what tool generates /dist/?

2023-04-29 16:29 UTC, FunctionDJ commented on .nvmrc
i know about nvm but that's used individually and on the project-level pnpm checks the node version via package.json.
so i don't see the need for this config file.

2023-04-29 16:34 UTC, onetrickwolf commented on .gitignore
> +/dist/
`pnpm build` genetates a dist for me on main

2023-04-29 19:04 UTC, megagreg72 approved these changes
lgtm

2023-04-29 21:22 UTC, FemboyDeveloper commented
LGTM as well, don't see a reason not to merge it with main already/

2023-04-29 22:25 UTC, onetrickwolf commented
@FemboyDeveloper I am "You’re not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request." but I may be blocked by @FunctionDJ review but yeah all set the merged whenever 👍

2023-04-30 01:39 UTC, leekahung reviewed
Minor stuff, see feedback.

2023-04-30 01:39 UTC, leekahung commented on CONTRIBUTING.md
>  Currently the project intends to recreate AWBW but with 2023 technology. Meaning we want to have a live league that works smoothly, a hot from the oven UI/UX thats reponsive and streamlines games, be
Typo with "that's responsive" not "thats reponsive".

And what does it mean by "hot from the oven".

2023-04-30 02:02 UTC, onetrickwolf commented on CONTRIBUTING.md
>  Currently the project intends to recreate AWBW but with 2023 technology. Meaning we want to have a live league that works smoothly, a hot from the oven UI/UX thats reponsive and streamlines games, be
Nice catch but I didn't write this content, changes to [CONTRIBUTING.md](https://github.com/WarsWorld/WarsWorld/pull/91/files/c3dea4d1438f55f8a574fe716542e648b01326d1#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055) were only made due to prettier fixes to make the build pass. Perhaps best addressed in another PR?

2023-04-30 02:09 UTC, leekahung commented on CONTRIBUTING.md
>  Currently the project intends to recreate AWBW but with 2023 technology. Meaning we want to have a live league that works smoothly, a hot from the oven UI/UX thats reponsive and streamlines games, be
Yeah, I think we can do that.

2023-04-30 15:39 UTC, FemboyDeveloper approved these changes
Okay, I'm going to resolve the conflicts and merge to main.

2023-04-30 15:47 UTC, merged