Update NextAuth
WarsWorld/WarsWorld pull request #93
Opened 2023-04-30 07:06 UTC by MatthewKuKanich

Rewrote the Next-Auth API/auth script to include a GitHub and Google OAuth sign-in provider, as well as added a passwordless email sign-in for backup access. I added a pages option with the sign-in and sign-out pages linked (will add those later). I also added a callbacks option, currently there is only the Sign-in callback which will be modified. I plan on using the callbacks to keep track of the session token to allow for account linking (Using Discord for sign-in, then converting to a regular User). I will do this with a JWT and session decryption callback.

2023-04-30 18:34 UTC, FunctionDJ requested changes

2023-04-30 18:34 UTC, FunctionDJ commented on src/pages/api/auth/[...nextauth].ts
> +const providers = [];
doesn't removing the type make TS infer `providers` type to be `never[]`?

2023-04-30 18:34 UTC, FunctionDJ commented on src/pages/api/auth/[...nextauth].ts
> +if (process.env.DISCORD_CLIENT_ID && process.env.DISCORD_CLIENT_SECRET) {
explicit checks like before (`!== undefined`) should be preferred over vague truthy checks

2023-04-30 18:34 UTC, FunctionDJ commented on src/pages/api/auth/[...nextauth].ts
> +      clientId: process.env.DISCORD_CLIENT_ID,
do the TS type gates work properly when you reference the env directly again like this instead of a variable like before?

2023-04-30 18:34 UTC, FunctionDJ commented on src/pages/api/auth/[...nextauth].ts
> +if (process.env.EMAIL_SERVER && process.env.EMAIL_FROM) {
is there anything that could break in development when providers that were enabled before are not enabled anymore? e.g. due to removing or changing the environment variables.
i was thinking that we could theoretically enforce specifying all environment variables, but then developers would need to specify a mail server too.

2023-04-30 18:34 UTC, FunctionDJ commented on src/pages/api/auth/[...nextauth].ts
> +if (process.env.EMAIL_SERVER && process.env.EMAIL_FROM) {
please update the .env example to document the new possible variables and their effect. e.g.:
```env
# Allows passwordless / email sign up and sign in. Optional.
# EMAIL_SERVER=
# EMAIL_FROM=
```

2023-04-30 18:34 UTC, FunctionDJ commented on src/pages/api/auth/[...nextauth].ts
> +    GoogleProvider({
does having google as a provider impact the users privacy any differently than having discord for example?

2023-04-30 18:34 UTC, FunctionDJ commented on src/pages/api/auth/[...nextauth].ts
> +  // The Email provider requires a database, we can comment this provider out until that is setup
that would just be our own database, wouldn't it?

2023-05-10 18:21 UTC, closed without merging

2023-05-10 18:24 UTC, FunctionDJ commented
ayo what, i deleted my branch and it closed this PR?
wasn't intentional.

2023-05-10 18:25 UTC, FunctionDJ commented
we can still recover this PR even if it's gonna be manual.

2023-05-10 22:14 UTC, FemboyDeveloper commented
smh function being toxic 😳

2023-05-10 23:19 UTC, MatthewKuKanich commented
All good, I'll update you

2023-05-10 23:44 UTC, MatthewKuKanich commented on src/pages/api/auth/[...nextauth].ts
> +      clientId: process.env.DISCORD_CLIENT_ID,
Yes, the environmental variables can be referenced directly. The type definitions can be set by both declaring them in code like before as well as in the type declaration file

2023-05-10 23:45 UTC, MatthewKuKanich commented on src/pages/api/auth/[...nextauth].ts
> +if (process.env.EMAIL_SERVER && process.env.EMAIL_FROM) {
I updated my code to set defaults. This should allow everything to function as normal if we decide to stop using or change the env variables.

2023-05-10 23:46 UTC, MatthewKuKanich commented on src/pages/api/auth/[...nextauth].ts
> +if (process.env.EMAIL_SERVER && process.env.EMAIL_FROM) {
Added that and matched it with the defaults

2023-05-10 23:54 UTC, MatthewKuKanich commented on src/pages/api/auth/[...nextauth].ts
> +    GoogleProvider({
We should be able to provide the user a just as private login and access control functionality using google as an additional provider. We will have control on user data collection (and lack thereof in our case). We will come up with the necessary scopes to enable us to collect as little data as possible, See: https://developers.google.com/identity/protocols/oauth2/web-server#identify-access-scopes

2023-05-10 23:56 UTC, MatthewKuKanich commented on src/pages/api/auth/[...nextauth].ts
> +  // The Email provider requires a database, we can comment this provider out until that is setup
Yes, I haven't fully looked into everything regarding our database, so I wasn't going to implement anything until I have a further understanding. I'd be happy to learn about it from you

2023-05-11 00:01 UTC, MatthewKuKanich commented on src/pages/api/auth/[...nextauth].ts
> +const providers = [];
No, since it's an empty array TS will infer ```providers``` type to be ```any[]```. Regardless, I added it back as a failsafe.

2023-05-11 00:12 UTC, MatthewKuKanich commented on src/pages/api/auth/[...nextauth].ts
> +if (process.env.DISCORD_CLIENT_ID && process.env.DISCORD_CLIENT_SECRET) {
Readded and reworked checking with a set of default variables