Updated Navbar styling/Include Dropdown menu for Match Lobby
WarsWorld/WarsWorld pull request #96
Opened 2023-05-01 07:01 UTC by leekahung

Have gone over styling for Navbar components and included Dropdown menus for Current Games and Completed Games. Have moved all Navbar related components into its own directory called Navbar.

New Dropdown menus uses HTML ids for internal routing (see below). Current Games and Completed Games are /match#current-games and /match#completed-games, respectively. I think there's a better way to route these in Next.js, but I'm not sure how. Feedback would be great!

https://user-images.githubusercontent.com/14917816/235410648-02105507-a9a6-4323-bf76-2e860692ece6.mov

Had accounted for when Navbar becomes burger menu below 768px width.

https://user-images.githubusercontent.com/14917816/235410708-e8d18535-2a16-469f-a345-179212ae4a42.mov

2023-05-03 21:07 UTC, leekahung commented
What is the current status of PR #96 at the moment?

2023-05-03 22:22 UTC, FemboyDeveloper requested changes
Just a few changes to do, most of the stuff looks good, keep it up dude! Really happy to have someone like you on the team!

2023-05-03 22:22 UTC, FemboyDeveloper commented on src/pages/match/index.tsx
> +        <div id="completed-games" className="completedGames">
Why is the id in kebab-case but the class in camelCase? Please make sure your casing is consistent.

2023-05-03 22:22 UTC, FemboyDeveloper commented on src/pages/match/index.tsx
> +        <div id="current-games" className="currentGames">
same issue here, make the casing consistent among the class and ID unless there's a specific reason for doing this

2023-05-03 23:11 UTC, leekahung commented on src/pages/match/index.tsx
> +        <div id="current-games" className="currentGames">
No problem, I can do that. I'll make them consistent with camelCase.

2023-05-03 23:19 UTC, leekahung commented on src/pages/match/index.tsx
> +        <div id="completed-games" className="completedGames">
Updated to camelCase.

2023-05-06 14:25 UTC, FemboyDeveloper approved these changes
LGTM!

2023-05-06 14:25 UTC, merged