Setting placeholder pages for existing Links
WarsWorld/WarsWorld pull request #97
Opened 2023-05-02 00:45 UTC by leekahung

Establishing placeholders with basic styling and Navbar for Terms of Use and Donations. Linked About back to the original AboutPage for now.

All pages (with the exception of Login) now is linked to an established page instead of rerouting to "/" when clicked.

2023-05-02 13:42 UTC, FemboyDeveloper requested changes
Everything looks good to me, just have some questions before merging. Keep up the great work!!!

2023-05-02 18:35 UTC, leekahung commented on src/pages/terms/index.tsx
> +      <div className="@text-center @w-[500px]">
#text-center is text-align: center. It's not related to media queries.

The reason I'm placing each one inside a folder is in case we would need to expand on those in the future. Like If we want to jump to another page within that like for match. In these cases it'll be like a tutorial page or something inside howtoplay, so a route like /howtoplay/tutorial.

2023-05-03 21:07 UTC, leekahung commented
What is the current status of PR #97 at the moment?

2023-05-03 22:18 UTC, FemboyDeveloper approved these changes
LGTM

2023-05-03 22:18 UTC, merged