Backend/DB Merge
WarsWorld/WarsWorld pull request #99
Opened 2023-05-04 16:45 UTC by FemboyDeveloper

Finally we have the one and only backend/db made by function, finally coming to main after one very extensive code review.

2023-05-04 17:14 UTC, FemboyDeveloper reviewed
@FunctionDJ left some comments, will continue to review later.

2023-05-04 17:14 UTC, FemboyDeveloper commented on src/server/emitter/create-emitter.ts
> +export const createEmitter = <D extends { matchId: string }>() => {
could you add some comments to this file? I don't understand what is happening here, it seems that we are unsubscribing? and then subscribing back?

2023-05-04 17:14 UTC, FemboyDeveloper commented on src/server/emitter/event-emitter.ts
> +import { EmittableEvent } from "shared/types/events";
I take this file handles creating an event emitter? why not put it inside create-emitter?

2023-05-04 17:14 UTC, FemboyDeveloper commented on src/server/main-production.ts
> +    }
Same as before, could you put some comments on this file? not sure exactly what it is doing, rebuilding the server?

2023-05-04 17:14 UTC, FemboyDeveloper commented on src/server/match-logic/apply-event-to-match.ts
> +};
is this a WIP? Seems like its missing stuff which is okay

2023-05-04 17:14 UTC, FemboyDeveloper commented on src/server/match-logic/server-match-logic.ts
> +export const getNextAvailablePlayerSlot = (matchState: BackendMatchState) => {
One comment describing this script is meant to check what the next playerSlot is (such as that you have 4 players in a match, people join in and the playerSlots (turn order) starts changing/getting occupied) would be very helpful

2023-05-04 17:30 UTC, WesKrug commented on src/pages/_app.tsx
>      <SessionProvider session={pageProps.session}>
This is next auth stuff. It makes it so the user's session is always available in the app, I believe.

2023-05-04 22:23 UTC, leekahung reviewed
Alright, I've gone over as much as I could on these files. Mainly just feedback comments rather than change requests.

2023-05-04 22:23 UTC, leekahung commented on src/server/match-logic/apply-event-to-match.ts
> +};
I think we can add a TODO comment on Line 8 that it's WIP

2023-05-04 22:23 UTC, leekahung commented on src/frontend/match/main.tsx
> +const spriteURLMap: Record<string, string> = {
I see that we're being more explicit for units (i.e. Infantry, Tanks, etc.).

Should we make these explicit as well to make it consistent with other assets? Or it this more related to how the tile files are structured and named and we can just keep this as is?

I'm fine with either.

2023-05-04 22:23 UTC, leekahung commented on src/server/routers/map.ts
> +      throw new Error("Map must be playable by at least 2 players");
Just something I've been thinking about, but doesn't need to be implemented now.

If we were to make a tutorial map for How to Play, we would need to make a map where the numberOfPlayers equals 1.

We could make a new subroutine for this scenario once we get there. Perhaps we could add a TODO comment related to that?

2023-05-04 23:27 UTC, FunctionDJ commented on src/pages/api/auth/[...nextauth].ts
> -    clientId: '1095434263308025978',
😀

2023-05-04 23:27 UTC, FunctionDJ commented on prisma/seed.ts
> +  importAWBWMap({
yes

2023-05-04 23:27 UTC, FunctionDJ commented on src/server/common-server.ts
> +  process.on("SIGTERM", () => {
it's a node.js process event (e.g. when pressing ctrl + c)

2023-05-04 23:29 UTC, FunctionDJ commented on src/server/emitter/create-emitter.ts
> +export const createEmitter = <D extends { matchId: string }>() => {
read up on JavaScript event emitters. the code here is a typesafe implementation of the same principal. you can subscribe to events with a callback function that will be called when those events occur.

2023-05-04 23:30 UTC, FunctionDJ commented on src/server/emitter/event-emitter.ts
> +import { EmittableEvent } from "shared/types/events";
create-emitter can generaty many emitters with different types. this one here is a specific instance with defined types.

2023-05-04 23:32 UTC, FunctionDJ commented on src/frontend/utils/use-local-storage.ts
> +import { useState } from "react";
doesn't matter right now, eventually we will probably have a folder.

2023-05-04 23:33 UTC, FunctionDJ commented on src/pages/index.tsx
> +      <h1>WarsWorld</h1>
then we don't have an index page.
i think what you mean is to move this somewhere else for the merge because i think we have a proper homepage in main.

2023-05-04 23:34 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
> +  return <PixiMatch />;
pixi only for the game board (tiles, units), not much else if anything.

2023-05-04 23:34 UTC, FunctionDJ commented on src/server/routers/map.ts
> +      throw new Error("Map must be playable by at least 2 players");
not for MVP

2023-05-05 02:17 UTC, leekahung commented on src/pages/index.tsx
> +      <h1>WarsWorld</h1>
Yep. Was thinking since we'll have a proper home page soon, we could just move all this into the Match Page or something of the sort.

2023-05-05 02:24 UTC, leekahung commented on src/pages/match/[matchId].tsx
> +  return <PixiMatch />;
Ah okay. If that's the case, I think we could refactor the component for Player Box (Lines 21 to Lines 82) from [matchId].tsx into it's own component and place it in inside /src/components/match/ or /src/frontend/match/.

We can bring it back out once we start building Match Page again.

2023-05-05 02:26 UTC, leekahung commented on src/pages/match/[matchId].tsx
> -const PlayerBox = ({
Perhaps we can save this component and refactor it out since Pixi is going to affect the map grid and not Player Box.

2023-05-05 02:26 UTC, leekahung commented on src/server/routers/map.ts
> +      throw new Error("Map must be playable by at least 2 players");
Yeah, not for now.

2023-05-05 02:27 UTC, leekahung requested changes
See feedback for /src/pages/match/[matchId].tsx.

All other answer looks good to me.

2023-05-05 03:30 UTC, megagreg72 commented
When I try to run this locally with `pnpm dx` I get the following error:
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\Users\bgauc\workspace\WarsWorld\.env
Rebuilding server state...
prisma:query SELECT "public"."Match"."id", "public"."Match"."leagueType", "public".
"Match"."status", "public"."Match"."mapId", "public"."Match"."playerState", "public
"."Match"."chatIsPublic", "public"."Match"."createdAt", "public"."Match"."playerId"
 FROM "public"."Match" WHERE "public"."Match"."status" <> $1 OFFSET $2
Rebuilding server state done.
Development mode: tRPC listening on ws://localhost:3001
event - compiled client and server successfully in 629 ms (294 modules)
➕➕ Connection (1)
wait  - compiling /api/auth/[...nextauth] (client and server)...
event - compiled successfully in 22 ms (57 modules)
createContext for unknown user
➕➕ Connection (2)
createContext for unknown user
prisma:query SELECT "public"."Map"."id", "public"."Map"."name", "public"."Map"."til
es", "public"."Map"."numberOfPlayers", "public"."Map"."createdAt" FROM "public"."Ma
p" WHERE 1=1 OFFSET $1
prisma:query SELECT "public"."Player"."id", "public"."Player"."name", "public"."Pla
yer"."secret", "public"."Player"."userId", "public"."Player"."preferences", "public
"."Player"."achievements" FROM "public"."Player" WHERE "public"."Player"."name"::te
xt LIKE $1 OFFSET $2
➖➖ Connection (1)
➖➖ Connection (0)
wait  - compiling /your-matches (client and server)...
➕➕ Connection (1)
➕➕ Connection (2)
createContext for unknown user
createContext for unknown user
prisma:query SELECT 1
prisma:query SELECT "public"."Map"."id", "public"."Map"."name", "public"."Map"."til
es", "public"."Map"."numberOfPlayers", "public"."Map"."createdAt" FROM "public"."Ma
p" WHERE 1=1 OFFSET $1
prisma:query SELECT "public"."Player"."id", "public"."Player"."name", "public"."Pla
yer"."secret", "public"."Player"."userId", "public"."Player"."preferences", "public
"."Player"."achievements" FROM "public"."Player" WHERE "public"."Player"."name"::te
xt LIKE $1 OFFSET $2
event - compiled client and server successfully in 139 ms (332 modules)
wait  - compiling /api/trpc/[trpc] (client and server)...
event - compiled successfully in 75 ms (118 modules)
createContext for unknown user
prisma:error
Invalid `prisma.player.findMany()` invocation:


The provided database string is invalid. Error parsing connection string: invalid p
ort number in database URL. Please refer to the documentation in https://www.prisma
.io/docs/reference/database-reference/connection-urls for constructing a correct co
nnection string. In some cases, certain characters must be escaped. Please check th
e string for any illegal characters.
Something went wrong
```

2023-05-05 11:56 UTC, FemboyDeveloper commented on src/frontend/styles/animations.sass
> +// ******************** ANIMATIONS ********************
@leekahung Yeah, I think we won't be using sass (or are we doing a mix?) either way its okay, I just know this old style sheets need to be deleted,

2023-05-05 12:02 UTC, FemboyDeveloper commented
@megagreg72 try using pnpm db-nuke (nukes the database), then retry using pnpm dx, if still doesn't work, I'd recommend using pnpm db-seed (it adds mock data to the db but this should run by default on pnpm dx afaik). Also! You can see your local database using pnpm studio (or just prisma studio).

2023-05-05 12:27 UTC, FemboyDeveloper commented on src/server/emitter/create-emitter.ts
> +export const createEmitter = <D extends { matchId: string }>() => {
Done, copy pasted your comment into the file

2023-05-05 12:38 UTC, FemboyDeveloper commented on src/server/main-production.ts
> +    }
@FunctionDJ not sure if you saw this.

2023-05-05 12:42 UTC, FemboyDeveloper commented on src/server/match-logic/server-match-logic.ts
> +export const getNextAvailablePlayerSlot = (matchState: BackendMatchState) => {
@FunctionDJ not sure if you saw this

2023-05-05 16:03 UTC, FunctionDJ commented on src/frontend/styles/animations.sass
> +// ******************** ANIMATIONS ********************
yes

2023-05-05 16:04 UTC, FunctionDJ commented on src/pages/_app.tsx
>      <SessionProvider session={pageProps.session}>
the provider provides the react context for the useSession hook which can be used to check in the client if the user is signed in.

2023-05-05 16:09 UTC, FunctionDJ commented on src/server/emitter/create-emitter.ts
> +export const createEmitter = <D extends { matchId: string }>() => {
i don't think writing comments about node.js features and concepts is a good idea.
(my bad for saying JavaScript event emitters. events are not part of JavaScript but they exist both in the browser as well as in node.js)

2023-05-05 16:14 UTC, FunctionDJ commented on src/server/main-production.ts
> +    }
i did, i just didn't get to replying to all comments yesterday.
this file is the main production file. it starts the next.js application (line 8), and bootstraps it along with the tRPC server to a basic http server (lines 28 for next and 31 for tRPC). everything else is basic node.js HTTP fluff.
it's worth mentioning that in line 12 it will rebuild the server state (load matches into memory) before proceeding to create the HTTP server.

2023-05-05 16:14 UTC, FunctionDJ commented on src/server/match-logic/apply-event-to-match.ts
> +};
WIP

2023-05-05 16:15 UTC, FunctionDJ commented on src/server/match-logic/server-match-logic.ts
> +export const getNextAvailablePlayerSlot = (matchState: BackendMatchState) => {
the filename isn't great, but the function name should be sufficient, no?

2023-05-05 16:15 UTC, FunctionDJ commented on .gitignore
> +.eslintcache
might or will?

2023-05-05 16:17 UTC, FunctionDJ commented on src/server/common-server.ts
> +  process.on("SIGTERM", () => {
i don't think comments about node.js fundamentals are a good idea.

2023-05-05 16:18 UTC, FunctionDJ commented on src/frontend/styles/match.module.css
then it will be deleted on merge, but deleting before merge is not the way to go about this.

2023-05-05 16:19 UTC, FunctionDJ commented on src/pages/index.tsx
> +      <h1>WarsWorld</h1>
this is something done during merge, not before.

2023-05-05 16:20 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
> +  return <PixiMatch />;
not sure what you mean. the file you've commented on is only 6 lines long.

2023-05-05 16:23 UTC, FunctionDJ commented on src/frontend/match/main.tsx
> +const spriteURLMap: Record<string, string> = {
i wasn't sure if we'll be getting different sprite sets with a different naming scheme.

2023-05-05 16:25 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
> -const PlayerBox = ({
not sure what you mean. the file you've commented on is only 6 lines long (copied this comment from the other one)

2023-05-05 16:26 UTC, FunctionDJ commented
@megagreg72 the error reason is in the logs: `The provided database string is invalid.`
your database env variables are not properly configured.

2023-05-05 19:38 UTC, leekahung commented on src/pages/match/[matchId].tsx
> -const PlayerBox = ({
Will this update not overwrite the current file in main?

It's currently 378 lines long right now on main with a lot of things we wish to replace with Pixi. But since you've mentioned you're only replacing the map grid, I thought we're keeping the Player Box somewhere? I don't see it being refactored out

2023-05-05 20:11 UTC, FunctionDJ commented on src/pages/match/[matchId].tsx
> -const PlayerBox = ({
i'll sort it out during merge.

2023-05-05 20:16 UTC, leekahung commented on src/pages/match/[matchId].tsx
> -const PlayerBox = ({
Got it. I think other than that, that's all from my end.

2023-05-05 20:18 UTC, leekahung approved these changes
All good. I think that's all from my end. Just need to deal with the merge conflicts.

2023-05-05 22:39 UTC, megagreg72 commented on src/server/common-server.ts
> +  process.on("SIGTERM", () => {
I know what SIGTERM is, but personally I prefer lots of comments, especially because we have people with various skill levels working on this.

2023-05-05 22:53 UTC, megagreg72 commented
thanks for the help. I ran
```
pnpm db-nuke
pnpm db-seed
pnpm dx
```
but I still see the same error.
I ran `pnpm studio`, which appears to use my `.env` file, and I can see some database records (8 players, 2 users, 2 maps).
```
pnpm studio

> warsworld@0.0.0 studio C:\Users\bgauc\workspace\WarsWorld
> prisma studio

Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Prisma Studio is up on http://localhost:5555
```
so maybe this is a windows issue? although I'm using WSL my setup might be a bit janky.

2023-05-05 23:18 UTC, megagreg72 commented on .gitignore
> +.eslintcache
I usually use a mac for work and haven't needed to add `.DS_Store` to any of my `.gitignore` files yet, but I can confirm it is a pretty common metadata file which macs generate.  I think we can wait to add stuff here until it actually affects someone.
```
The file .DS_Store is created in any directory (folder) accessed by the Finder application
```
from wikipedia

2023-05-06 22:02 UTC, FunctionDJ approved these changes

2023-05-07 00:50 UTC, FemboyDeveloper reviewed
@FunctionDJ Here are my last comments and requests... Having to read so much of your code has helped me understand your work far more. However, as said before, the lack of comments is a problem that hampers the maintainability of the project. Having our code be 1.5 or 2x the size isn't a problem for us. A bigger problem is devs not bothering to help because they need to spend their free time reading multiple files to understand what is happening/what were we thinking when almost none of the files have any comments or explanations in them.

Also albeit I know you had good intentions of not pushing into main until your work was "ready", it has resulted in a sloppy code review due to the enormous size of your pull request. It is better to follow best practices and make small PR/commits even if your code needs more work to be fully functional. Smaller PRs make it easier to catch issues earlier and make better code reviews.

Your work is extremely appreciated. I have learned a lot from talking to you and looking at your work. You truly demonstrate experience and knowledge in the field that I can only wish to have one day. Thanks to you, I've become a better developer and project manager.

2023-05-07 00:50 UTC, FemboyDeveloper commented on src/server/schemas/unit.ts
> +]);
What does this creatableInfantry/Mech and SoldierSchema? Seems a bit weird that we are putting each one of them into their own Schema like this, a comment to explain why would help alot since my mind just makes me think this is inneficient since I dont know why it was done this way

2023-05-07 00:50 UTC, FemboyDeveloper commented on src/server/schemas/unit.ts
> +]);
Stuff like this is very puzzling to people new to Zod

2023-05-07 00:50 UTC, FemboyDeveloper commented on src/server/trpc/middleware/player.ts
> +};
A comment explaining why would we need "development mode users" and where are they used would help newbies understand what exactly this is doing here.

2023-05-07 00:50 UTC, FemboyDeveloper commented on src/shared/match-logic/buildable-unit.ts
> +  ["sea", "lander"].includes(unitPropertiesMap[unit.type].movementType);
why does this include lander but not blackboat? is there anything special about landers?

2023-05-07 00:50 UTC, FemboyDeveloper commented on src/shared/match-logic/check-terrain.ts
> +}
so this is checking if the nextTile has an unit/isnt undefined and same w the initial tile and then we check they are not from different countries/playerSlots. Couldnt we just use 
``` nextTile?.unit?.playerSlot ``` instead?

2023-05-07 00:50 UTC, FemboyDeveloper commented on src/shared/match-logic/generate-attack-event.ts
> +  );
this whole section would benefit alot from comments stating this is making sure the attacker and defender information received is the sameposition/same as the information in the db (or thats what Im getting from this)

2023-05-07 00:50 UTC, FemboyDeveloper commented on src/shared/match-logic/get-changeable-tile-from-map.ts
> +};
you get a changeable tile from a tile? This concept is very confusing, is this like an unusedSilo become a usedSilo? Whats that hp: 20 at the bottom? This seems hard to grasp

2023-05-07 00:50 UTC, FemboyDeveloper commented on src/shared/match-logic/tiles.ts
> +};
is there really no better way to do this in typescript? im astonished we are writing all this tile properties like this instead of using object or an array.

2023-05-07 05:25 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> +};
I'll work on this in a branch-of-branch

2023-05-07 07:53 UTC, megagreg72 commented on src/shared/match-logic/tiles.ts
> +};
https://github.com/WarsWorld/WarsWorld/pull/106/files

2023-05-07 17:50 UTC, FunctionDJ requested changes

2023-05-07 17:50 UTC, FunctionDJ commented on src/server/schemas/army.ts
> + "orange-star", "blue-moon", "green-earth", "yellow-comet", "black-hole", "red-fire", "grey-sky", "brown-desert", "amber-blaze", "jade-sun", "cobalt-ice", "pink-cosmos", "teal-galaxy", "purple-lighti
no prettier 💀

2023-05-07 17:51 UTC, FunctionDJ commented on src/server/schemas/army.ts
> + "orange-star", "blue-moon", "green-earth", "yellow-comet", "black-hole", "red-fire", "grey-sky", "brown-desert", "amber-blaze", "jade-sun", "cobalt-ice", "pink-cosmos", "teal-galaxy", "purple-lighti
also we don't have any assets for these army types yet.

2023-05-07 18:11 UTC, FemboyDeveloper commented on src/server/schemas/army.ts
> + "orange-star", "blue-moon", "green-earth", "yellow-comet", "black-hole", "red-fire", "grey-sky", "brown-desert", "amber-blaze", "jade-sun", "cobalt-ice", "pink-cosmos", "teal-galaxy", "purple-lighti
I think it's sorta wasteful to put them on top of each other and these elements wont be used often so it didnt matter much to me. Also we do have the assets for those army types. We are preparing the sprite sheet with Enigmatic and Sicilica to have everything ready for development.

Also please check the other comments, I'd like to add your work to main soon! ❤️❤️❤️

2023-05-08 02:55 UTC, megagreg72 commented on src/shared/match-logic/buildable-unit.ts
> +  ["sea", "lander"].includes(unitPropertiesMap[unit.type].movementType);
"Lander" is the name of the "movement type" defined here
https://awbw.fandom.com/wiki/Terrain
but I think that blackboats and landers both have this "movement type".
So I think this is just confusion because the movement type happens to have the same name as a unit.
We could diverge from the "movement type" names used by wiki if we think doing so would add clarity.

2023-05-08 03:04 UTC, megagreg72 commented on src/shared/match-logic/buildable-unit.ts
> +    attackRange: [0, 3], // TODO is this suitable for how we'll handle it?
```suggestion
// TODO: Black Bombs do not attack other units, and instead have an "Explode" command
```

2023-05-08 03:21 UTC, megagreg72 commented on src/shared/match-logic/buildable-unit.ts
> +    attackRange: [0, 3], // TODO is this suitable for how we'll handle it?
I don't think we want to treat this like an attack.

2023-05-08 05:17 UTC, megagreg72 commented on src/shared/match-logic/buildable-unit.ts
> +  }
```suggestion
  if (movementType === "air") {
    if(unit.type === "battleCopter" || unit.type === "transportCopter") {
      return 2;
    }
    else if(unit.type === "stealth" && unit.hidden) {
      return 8;
    }
    return 5;
  }
```

2023-05-08 05:18 UTC, megagreg72 commented on src/shared/match-logic/buildable-unit.ts
> +  }
fix copter fuel, based on wiki

2023-05-10 17:00 UTC, merged